### ISSUE TITLE
Links on RTD API reference are dead

### ISSUE THREAD

**Issue by msschwartz21** [OpenPIV/openpiv-python#102]
https://openpiv.readthedocs.io/en/latest/src/api_reference.html#the-openpiv-tools-module

The links to in detail API references are not active.

**Comment by alexlib** [comment]
Thanks for noticing @msschwartz21 - actually I do not know how to fix it. Do you have any idea?

**Comment by alexlib** [comment]
resolved
https://openpiv-python.readthedocs.io/en/latest/src/api_reference.html
