### ISSUE TITLE
Sub-pixel peak position calculation failure

### ISSUE THREAD

**Issue by bschumac** [OpenPIV/openpiv-python#108]
Hi, its me again :-)
I am currently experimenting with the find_subpixel_peak_position function. 
The problem of that function is if the find_first_peak() function returns a corner value of the correlation matrix then the sub-pixel peak position is set to (0,0) which in this sense is not correct at all. 
I am proposing therefore for corner cases a change of the found peak value by 1 px to the inside so the calculation can be made.
I will try to request that change through github and push the changed pyprocess.py to the repository if you allow.

Cheers,
Ben

**Comment by alexlib** [comment]
@bschumac great - I am not aware of this corner problem. Could you please make a small example to visualize the problem? Thanks

**Comment by vzickus** [comment]
@bschumac That would be very useful to know. I haven't used OpenPIV for a while, but I thought that if a peak was detected at the edges, it would return the "default" peak indicating no motion?

**Comment by alexlib** [comment]
We solved the corner problem in #165. we eliminate the peaks that are on the borders. See also a notebook in the /examples that demonstrates the solution
