### ISSUE TITLE
openpiv not working for my dataset

### ISSUE THREAD

**Issue by Arkajyoti** [OpenPIV/openpiv-python#112]
Hi, 
I am very new to PIV and coding in general so please bear with me. I have a dataset that is a video taken by a single camera under constant led illumination. I have broken them down into frames (dt=.06) and am trying to generate the velocity vectors, so far unsuccessfully. (the vectors don't seem to represent fluid motion in the actual video). 
video: 

Code: 
[piv initial2.txt](https://github.com/OpenPIV/openpiv-python/files/3677225/piv.initial2.txt)

Is there any way to save the displayed vector fields? Also, for outliers and sig2noise methods, are there any other options than local mean and peak2peak?

Thank you in advance

**Comment by vzickus** [comment]
Hi @Arkajyoti, I think it's best you use openpiv-users@googlegroups.com mailing list for questions like that (GitHub issues are generally for technical issues with the code like bugs etc.)

It's been a while since I've done PIV, but just by looking at the data I think there are quite a few issues with it. Firstly, there seems to be quite a lot of out-of-focus particles, this means you will likely have a large _depth of correlation_ which will under/overestimate your flow. Secondly, it seems to me you have a lot of diffusion. The general PIV assumption is that your particles between frames remain in the same relative locations within a particle _group_. The book "Particle Image Velocimetry" by Adrian and Westerweel or "Particle Image Velocimetry: A Practical Guide " by Raffel et al. explain these issues well, and suggest possible way to alleviate these issue. I think it would be a good idea to familiarise with the theory a bit more, as there are subtle effects that can yield erroneous results.

**Comment by Arkajyoti** [comment]
@vzickus Thank you very much Vytas. I will look into the books and go through the details. Regarding diffusion, these are biological cells that move on their own. So, it is not always the case that they remain locally relative. These things I would like to discuss as I understand more about the process. Just out of curiosity, do you need a strong mathematical background to understand the theory? And next time I have problems, I will surely put them in google groups. 

Thank you again
Cheers

**Comment by alexlib** [comment]
Hi @Arkajyoti 
What were your parameters? 
I have copied the openpiv-python example from here https://github.com/alexlib/openpiv-python-example 
and without changing parameters, got a very nice flow field. 

![image](https://user-images.githubusercontent.com/747110/65982423-fe4fc480-e483-11e9-9931-aa4a4a1d0832.png)

using `tools.display_vector_field('test.txt', scale=.1, width=0.0025)`

**Comment by alexlib** [comment]
you can see the notebook on Google Colaboratory 
https://colab.research.google.com/drive/1G15182j60La03aDvuM4hrh-uvstEyfo-

**Comment by alexlib** [comment]
<script src="https://gist.github.com/alexlib/eaa5708c9a9d278b9a65e90c313aafec.js"></script>

**Comment by alexlib** [comment]
![image](https://user-images.githubusercontent.com/747110/65988531-aff4f280-e490-11e9-85ad-f1c031511a25.png)

**Comment by Arkajyoti** [comment]
@alexlib Hi, thank you for your reply. I went through your tutorials  (https://github.com/OpenPIV/openpiv-python) and tried to replicate the code but varied the parameters randomly to see which gave the best output. But none of them seemed to match. Is there any protocol to optimize the parameters like window size, search size, kernel size, scaling, etc.? Also, where can I find a detailed description of what each of these functions is doing? 
I just started acquiring these images and wanted to see how the code worked. Now I am acquiring better images and started going deep into the theory but it would be helpful to get insight into the python modules as well. 
Thank you very much for your help.

**Comment by alexlib** [comment]
@Arkajyoti - we use the standard names. if you take a book or some online resource on PIV - you get it all very quickly. 
the way to understand the functions is to look into the code comments and look here 
https://openpiv.readthedocs.io/en/latest/

**Comment by Arkajyoti** [comment]
Hi Alex, Thank you for the suggestion. I am reading Particle Image Velocimetry: A Practical Guide " by Raffel et al. and hope to know more about this process. 
Here are a few quick questions: 1) Without any calibration, how do you determine parameters like window size, sig2noise threshold, and scaling factors? Is it trial and error?
2) Is there any way to generate and save intermediate flow fields for multipass (for visualizing and analysis purposes)? 
3) For my current dataset, the txt file shows around 43 x,y co-ordinates, repeated in multiple sets. For each set, it has variable u,v values. So, is each set of x,y,u,v unique for each arrow? 
Images: 
![gif](https://user-images.githubusercontent.com/30227887/66919083-f7e35000-f020-11e9-9624-a267fc573079.gif)
Result:
![Piv](https://user-images.githubusercontent.com/30227887/66919129-0a5d8980-f021-11e9-9885-4af2721f1c41.png)
[Note: this is the result from a single pass iteration] 
Ps: Is there any way to contact you outside github (say via email)?

**Comment by alexlib** [comment]
you can contact me by e-mail alexlib at tauex dot tau dot ac dot il (if the questions are about collaboration, our help with the analysis, etc.) or better via forum https://groups.google.com/forum/?hl=en#!forum/openpiv-users if it's about general PIV things - the answers could help others. 

1. calibration is needed to know pixel/meter scale
2. window size depends on the size and number of your particles or the region of the interest (in your case these are not particles). sig2noise you don't know - you run first - look at the results and then decide what threshold will keep the good ones and remove those that are completely wrong. most of the parameters are really trial and error 
3. every row is x,y position of the vector and u,v are length of the vector along x,y coordinates
4. your images do not look like PIV images and it's difficult to know how to process it. Depending on what you want to achieve - we could talk about us looking a bit closer into it (e.g. scientific collaboration or consultancy). it seems that you need to develop a bit of your own code.

**Comment by Arkajyoti** [comment]
Hi Alex,

Thank you for the reply. We are working with active matters of different shapes and motion (which we are trying to capture) so indeed the 1st image set is different from the last set. The basic idea was to check as a first pass if and how well the python PIV module works on these systems. I wanted to make sure that I am also understanding the modules clearly, using representative parameters and modify them where trial and error is required.
I know that these are not how traditional PIV images look like and will try to add some lines and to come up with a modified version in future.
Regards
Arkajyoti
