### ISSUE TITLE
tools.display_vector_field Error

### ISSUE THREAD

**Issue by bramgibs** [OpenPIV/openpiv-python#122]
When trying to reproduce tutorials, I get an error with tools.display_vector_field when I swap 'on_img = True'. Attached is the script that I am working from. Below is the error. 

[testing.zip](https://github.com/OpenPIV/openpiv-python/files/4087491/testing.zip)
---
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    tools.display_vector_field('test1.vec', on_img = True, scale=75, width=0.0035)
  File "/home/user/miniconda3/lib/python3.7/site-packages/openpiv/tools.py", line 78, in display_vector_field
    im = imread(image_name)
  File "/home/user/miniconda3/lib/python3.7/site-packages/openpiv/tools.py", line 119, in imread
    im = _imread(filename)
  File "/home/user/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 1417, in imread
    with Image.open(fname) as image:
  File "/home/user/miniconda3/lib/python3.7/site-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'None'

**Comment by alexlib** [comment]
@bramgibs the error says you provide a non-existing image, can you please check it?

**Comment by alexlib** [comment]
@bramgibs  not sure if it's a bug in the original tutorial, the line should be:
```
# plt.imshow(frame_a,cmap=plt.cm.gray)
tools.display_vector_field('test1.vec', on_img = True, image_name='exp1_001_a.bmp', scaling_factor = 96.52)

```

**Comment by alexlib** [comment]
you're welcome to see it here: https://colab.research.google.com/drive/1p8EK58oJED8JIxi6Pv84zELPi1wUH7ZE

**Comment by alexlib** [comment]
https://colab.research.google.com/drive/1p8EK58oJED8JIxi6Pv84zELPi1wUH7ZE

**Comment by yuriishizawa** [comment]
@alexlib I think that currently the option "on_img" is plotting the figure inverted related to horizontal axis. How can I fix it?

**Comment by alexlib** [comment]
@yuriishizawa  not sure about it - can you show me an example, please?

**Comment by Zecolas** [comment]
@yuriishizawa I think I've spot out the same problem as you mentioned. I basically save the y coordinates as -y in the output file to “fix” it...
      openpiv.tools.save(x, -y, u, v, ’exp1_001.txt’ )

**Comment by alexlib** [comment]
> @yuriishizawa I think I've spot out the same problem as you mentioned. I basically save the y coordinates as -y in the output file to “fix” it...
> openpiv.tools.save(x, -y, u, v, ’exp1_001.txt’ )

Please show me some clear example of the problem. I have tested it and didn’t find any issue.

**Comment by alexlib** [comment]
solved. new tools.display_vector_field should work. see 0.23.1 version
