### ISSUE TITLE
sig2noise threshold in WiDIM

### ISSUE THREAD

**Issue by ajpetersen25** [OpenPIV/openpiv-python#125]
I'm trying to use process.WiDIM for some multi-pass PIV, but I'm unclear how to change some parameters like the sign2noise threshold in particular. Looking in process.c I found: "...the sig2noise for which the threshold is 1.5" but does that mean I can't adjust it?
Thanks for the help!

**Comment by alexlib** [comment]
Hi @ajpetersen25 - good question. you're right that in this method

https://github.com/OpenPIV/openpiv-python/blob/f4ee0dd6b8432a22ceda5a496be9938e8b2d6a4d/openpiv/process.pyx#L536

the 1.5 value is hard-coded. 

There are two possible solutions: 
a) open a feature request and/or help me to fix it with a pull request
b) move to the more advanced and probably better WINDEF method

https://github.com/OpenPIV/openpiv-python/blob/master/openpiv/examples/tutorials/example_windef_run.py

I'd be very much glad to follow where OpenPIV helps to your research. Keep us posted on the mailing list.

**Comment by ajpetersen25** [comment]
WINDEF looks great in terms of being able to set all the different parameters, but it seems to require setting a file path full of images named in a "frame_a", "frame_b" pattern. But with time-resolved data, my images are simply named: frame1.tif, frame2.tif, etc. So how can I set the settings correctly with these images? Also is it just possible to run WINDEF just on two arrays I already have loaded into python or am I locked in to using windef.settings to specify file paths?

**Comment by alexlib** [comment]
@ajpetersen25 @TKaeufer  might be needed here for help. I already asked him to make the settings more general, so different options for file names or running it without settings. So it's a requested feature.

**Comment by alexlib** [comment]
@ajpetersen25  see https://github.com/OpenPIV/openpiv-python/tree/widim_sig2noise

**Comment by TKaeufer** [comment]
For now, the windef.settings can only be used for comparing A with B.
You can also open windef.py and modify it according to your needs.
windef.settings is just used to simplify the setup process. It collects the parameters and passes them to the windef.py

**Comment by alexlib** [comment]
Thanks @TKaeufer 
@ajpetersen25 - show us some of your images and we could try to make an example of using windef.py with your settings.

**Comment by alexlib** [comment]
@ajpetersen25 is your problem solved? if now, it's rather easy to fix

**Comment by alexlib** [comment]
WIDIM is retired. closing.
