### ISSUE TITLE
Wrong sign of V in PIV vectors

### ISSUE THREAD

**Issue by andimi** [OpenPIV/openpiv-python#128]
I was testing this library with 2 sample images where I created some dots moving towards the centre of the image. I noticed that the sign of the V vectors was incorrect, and noticed the minus sign in the code for extended_search_area_piv() .

v[I,J] = -( (i_peak - corr.shape[0]/2) - (search_area_size-window_size)/2 ) / dt

Is there a reason why the minus sign is there?

Best

**Comment by alexlib** [comment]
@andimi you refer to this line 
https://github.com/OpenPIV/openpiv-python/blame/91b4a0fd5c35a18d10a92fbb46f2cd29cb9e35df/openpiv/process.pyx#L191
but i'm not sure it's a wrong direction. 
can you please show us an example of why this is incorrect? 
i think this also related to the fact that the coordinate system of the image in Python as an array and its visual representation are different. visually it's top left corner origin and in an array it's according to the direction of the increasing values. So "positive V" is kind of not well defined.

**Comment by alexlib** [comment]
@andimi - maybe you're right. do you have a clear example of this bug?

**Comment by andimi** [comment]
Hi Alex,

Sorry for the late reply - I attached here two images: piv-ref.png and piv-test.png (although I think github renames them to xxx18c.png and xxx3d0.png respectively).
In those images there are dots that move towards the centre of the image from ref to test.

If you run the algorithm on those with standard parameters, as a PIV result you get that the dots move towards the centre in the x-axis but away from the centre in the y-axis. This is what made me think there could be a sign error for v.
 
I hope this helps, please let me know what you think!

Best,
Andrea

![piv-ref](https://user-images.githubusercontent.com/3579760/79563868-7dfe5300-80a5-11ea-9601-58aa9554118c.png)
![piv-test](https://user-images.githubusercontent.com/3579760/79563870-7e96e980-80a5-11ea-8e15-e8486071d3d0.png)

**Comment by andimi** [comment]
PS: Just to make those images clearer, here is the overlay of piv-ref.png (magenta) and piv.test (green).

![piv-overlay](https://user-images.githubusercontent.com/3579760/79564852-560fef00-80a7-11ea-8758-a8ebe7d950c8.png)

**Comment by alexlib** [comment]
Thanks @andimi but where the arrows? Please also tell me how is Openpiv installed for you

**Comment by alexlib** [comment]
These images are not good for PIV - could you please create a similar motion but with many small dots?

**Comment by alexlib** [comment]
https://youtu.be/S0_rhYuzQIY

**Comment by alexlib** [comment]
> PS: Just to make those images clearer, here is the overlay of piv-ref.png (magenta) and piv.test (green).
> 
> ![piv-overlay](https://user-images.githubusercontent.com/3579760/79564852-560fef00-80a7-11ea-8758-a8ebe7d950c8.png)

See https://youtu.be/S0_rhYuzQIY

Please update your openpiv version 

‘pip install openpiv==0.21.9’

**Comment by andimi** [comment]
Thanks in the video it looks like things are working fine!
Can I ask you what was changed?

I'll update the library! :)

**Comment by alexlib** [comment]
it's easy - compare the changes on github - but I didn't change things in the core of the code. All the things were as before. difficult to judge as I haven't seen your "wrong arrows".

**Comment by alexlib** [comment]
This line 
`v[I,J] = -( (i_peak - corr.shape[0]/2) - (search_area_size-window_size)/2 ) / dt` 
is correct - the fact is that coordinate system of matrix is 0,0 at the lower left corner so positive 'x' direction is from left to right and positive 'v' direction is from bottom to top. 

In image, on contrary, the 0,0 is usually at top left corner, so the "positive row change" is from top to bottom. And there is a `-` sign correction for this. 
but you only need to remember that if you want "the natural, visual" direction of the motion - as in your images, you're not working with the right-hand geometry system, and it'll generate problems later on when you analyse vorticity or strain, etc.

**Comment by andimi** [comment]
Thank you very much for the explanation and for fixing the sign!
