### ISSUE TITLE
Newer versions produce wrong results compared with the older versions 

### ISSUE THREAD

**Issue by ShabnamR** [OpenPIV/openpiv-python#143]
I realized image pairs analyzed with versions 0.21.8 and lower give different results than versions 0.22.0 ad 0.22.2. The results I am getting from versions 0.22.0 and later are physically not acceptable, while the earlier ones are all correct. It seems that the changes to replace_nans cause this issue.

**Comment by alexlib** [comment]
Please show the images you use - we tested it with the tutorial notebooks and it worked apparently.

**Comment by alexlib** [comment]
> I realized image pairs analyzed with versions 0.21.8 and lower give different results than versions 0.22.0 ad 0.22.2. The results I am getting from versions 0.22.0 and later are physically not acceptable, while the earlier ones are all correct. It seems that the changes to replace_nans cause this issue.

I cannot confirm your findings - I created now two environments and installed separately the latest version and the 0.21.8 version from pypi.org and both work on the first 3 test sets.

**Comment by ShabnamR** [comment]
Thanks a lot for checking! It could be that the case I am running is more sensitive. I am trying to image Taylor Couette vortices and the mean flow is perpendicular to the imaging plane. Still, I have enough time resolution to make sure I am not losing particles due to out of plane motion.

I have made docker images of multiple versions and have attached V0.21.3a and V0.22.0 results here. It seems that I have to use np.flipud() with the V0.22.0 to get similar results as V0.21.3a at the beginning (Run20_1 images). (Is there something I need to specify that I have missed?)

However, at the level of replacing outliers, the results of the V0.22.0 affects the mean of each row of the array (Run20_2 images). So when subtracting the mean flow, the older versions give the full vortices and the newer versions give partial vortices or none(Run20_stream images). Because of the cylindrical nature of the flow, I cannot just subtract the mean of the entire array from every element and have to subtract the mean of each row from itself. 

I have attached the files here. 
[TestCase.zip](https://github.com/OpenPIV/openpiv-python/files/4944002/TestCase.zip)

**Comment by alexlib** [comment]
I see some differences now. Indeed we need to check. 
I've created this repository with two notebooks and tried those with 0.22 and 0.21.8 and I see that u0,v0 is already different. Need to dig deeper into it. 
@AndreasBauerGit please also take a look at these images

https://nbviewer.jupyter.org/github/alexlib/testcase_outofplane_PIV/blob/master/PIV_test_v0218.ipynb
https://nbviewer.jupyter.org/github/alexlib/testcase_outofplane_PIV/blob/master/PIV_test_v022.ipynb

@ShabnamR and @AndreasBauerGit - you're welcome to run tests on this one 
https://github.com/alexlib/testcase_outofplane_PIV

**Comment by ShabnamR** [comment]
> I see some differences now. Indeed we need to check.
> I've created this repository with two notebooks and tried those with 0.22 and 0.21.8 and I see that u0,v0 is already different. Need to dig deeper into it.
> @AndreasBauerGit please also take a look at these images
> 
> https://nbviewer.jupyter.org/github/alexlib/testcase_outofplane_PIV/blob/master/PIV_test_v0218.ipynb
> https://nbviewer.jupyter.org/github/alexlib/testcase_outofplane_PIV/blob/master/PIV_test_v022.ipynb
> 
> @ShabnamR actually 0.22.0 version looks much better.
> 
> @ShabnamR and @AndreasBauerGit - you're welcome to run tests on this one
> https://github.com/alexlib/testcase_outofplane_PIV

Sure, thanks! I'll try again and see where the difference could be. 

But somehow the in 0.22 arrows seem to be flipped with respect to the apparent velocities; larger arrows need to be close to the textured wall and with direction toward the smooth wall (Downward in the first 3 imshow() images).

**Comment by alexlib** [comment]
> Thanks a lot for checking! It could be that the case I am running is more sensitive. I am trying to image Taylor Couette vortices and the mean flow is perpendicular to the imaging plane. Still, I have enough time resolution to make sure I am not losing particles due to out of plane motion.
> 
> I have made docker images of multiple versions and have attached V0.21.3a and V0.22.0 results here. It seems that I have to use np.flipud() with the V0.22.0 to get similar results as V0.21.3a at the beginning (Run20_1 images). (Is there something I need to specify that I have missed?)
> 
> However, at the level of replacing outliers, the results of the V0.22.0 affects the mean of each row of the array (Run20_2 images). So when subtracting the mean flow, the older versions give the full vortices and the newer versions give partial vortices or none(Run20_stream images). Because of the cylindrical nature of the flow, I cannot just subtract the mean of the entire array from every element and have to subtract the mean of each row from itself.
> 
> I have attached the files here.
> [TestCase.zip](https://github.com/OpenPIV/openpiv-python/files/4944002/TestCase.zip)

@AndreasBauerGit - could you take a look. I see that 0.21.8 and 0.22.0 create different results for these images, but I cannot actually point out the problem. For me though @ShabnamR  - the 0.22.0 version looks much better

**Comment by alexlib** [comment]
I suspect it might be related to this one, where we moved from 0.21.8b to 0.21.8c, but not yet clear what is different, unless some inputs are passed in a wrong way. The code has not changed I believe, except indeed the "direction issue" and I guess it's what @ShabnamR refers to:  

`
It seems that I have to use np.flipud() with the V0.22.0 to get similar results as V0.21.3a at the beginning (Run20_1 images)
`

https://github.com/OpenPIV/openpiv-python/pull/130

**Comment by ShabnamR** [comment]
@AndreasBauerGit and @alexlib, I just ran 0.21.8 and 0.21.8b, 0.21.8b gives very similar results as 0.21.3a that I posted earlier, but everything changes from 0.21.8 (is this the c version?). For 0.21.8 I need to use flipud() to get the directions correctly. The arrows, around the point that goes to zero velocity, should bend inward as if they are enveloping a circle, but the 22.0 version in the notebook they bend outward (like a hyperbola). 

These are with 0.21.8b without using flipud():
![V21_8b_Run20_1_00200](https://user-images.githubusercontent.com/16419185/87881792-9abe6580-c9c9-11ea-846a-11531476b2bf.png)
![V21_8b_Run20_2_00200](https://user-images.githubusercontent.com/16419185/87881793-9b56fc00-c9c9-11ea-8a7d-b7d4a578e26d.png)

These are with 0.21.8 with flipud():

u0 = np.flipud(u0)/80*2*0.001
v0 = np.flipud(v0)/235*8.225*0.001

![V21_8_Run20_1_00200](https://user-images.githubusercontent.com/16419185/87881794-9bef9280-c9c9-11ea-9d55-536e2db35495.png)
![V21_8_Run20_2_00200](https://user-images.githubusercontent.com/16419185/87881795-9bef9280-c9c9-11ea-940e-bc636e436286.png)

**Comment by alexlib** [comment]
@ShabnamR if this is the only thing, then I think we know why it is so and we would like to stay with the new version. What is recommended I think is to use our `tools` (I just don't know the real scaling factor, just tried something that seems working). So if we plot it over the image, without rotation and without flipping 

`
openpiv.tools.save(x, y, u2, v2, mask, 'tmp2.txt' )
fig, ax = plt.subplots(figsize=(12,12))
openpiv.tools.display_vector_field('tmp2.txt', ax=ax, scaling_factor=20000, scale=1, width=0.0025, on_img=True, image_name='tmp.png');
`
and the result is 


![image](https://user-images.githubusercontent.com/747110/87882326-07585500-ca08-11ea-8df0-cda3f08b055c.png)

**Comment by ShabnamR** [comment]
@alexlib That makes sense, thanks for the explanation! 

But that does not solve the difference I get between the two versions, here's the result after replacing outliers for 0.21.8b 

![V21_8b_Run20_2_00200](https://user-images.githubusercontent.com/16419185/87882786-95b0e480-c9d0-11ea-9109-45679dc2ffaa.png)

and this is for 0.22.0

![V22_0_Run20_2_00200](https://user-images.githubusercontent.com/16419185/87882796-9ea1b600-c9d0-11ea-952a-b200b3d8d341.png)

As you can see the results are different and this difference causes issues when I need to further manipulate the results to get the vortices that I need to visualize. The final streamlines then for 0.21.8b

![V21_8b_Run20_Stream_00200](https://user-images.githubusercontent.com/16419185/87882829-e7596f00-c9d0-11ea-9b44-a8b8f25e1d51.png)

and for 22.0

![V22_0_Run20_Stream_00200](https://user-images.githubusercontent.com/16419185/87882835-f04a4080-c9d0-11ea-876f-0ebd3ca602ba.png)

are different and 22.0 cannot capture the two vortices on the right-hand side. Between these two the results from 0.21.8b are physically closer to the phenomenon than the ones from 0.21.8 or 0.22.0.

**Comment by alexlib** [comment]
> @alexlib That makes sense, thanks for the explanation!
> 
> But that does not solve the difference I get between the two versions, here's the result after replacing outliers for 0.21.8b
> 
> ![V21_8b_Run20_2_00200](https://user-images.githubusercontent.com/16419185/87882786-95b0e480-c9d0-11ea-9109-45679dc2ffaa.png)
> 
> and this is for 0.22.0
> 
> ![V22_0_Run20_2_00200](https://user-images.githubusercontent.com/16419185/87882796-9ea1b600-c9d0-11ea-952a-b200b3d8d341.png)
> 
> As you can see the results are different and this difference causes issues when I need to further manipulate the results to get the vortices that I need to visualize. The final streamlines then for 0.21.8b
> 
> ![V21_8b_Run20_Stream_00200](https://user-images.githubusercontent.com/16419185/87882829-e7596f00-c9d0-11ea-9b44-a8b8f25e1d51.png)
> 
> and for 22.0
> 
> ![V22_0_Run20_Stream_00200](https://user-images.githubusercontent.com/16419185/87882835-f04a4080-c9d0-11ea-876f-0ebd3ca602ba.png)
> 
> are different and 22.0 cannot capture the two vortices on the right-hand side. Between these two the results from 0.21.8b are physically closer to the phenomenon than the ones from 0.21.8 or 0.22.0.

You're right, these are different. I do not really know the difference, but I'd like to test it thoroughly. How many image pairs do you use for this case? If you don't mind to share the data and the docker images you use - I'd try to dive into it. From the software point of view, we believe the 0.22.0 version is better, it has more features and it passes all the same tests. We have not tried it for a large set. I guess that your differences are more due to the averaging, etc. rather than basic PIV stuff, but we need to see it first.

**Comment by alexlib** [comment]
@ShabnamR actually what you need to do to plot it with quiver is: 

```
fig=plt.figure(figsize=(10, 5), dpi= 80, facecolor='w', edgecolor='k')
plt.quiver(x,y,u2,-v2,
           angles='xy', scale_units='xy', scale = 160,
           headlength = 3, headwidth = 2, headaxislength = 3, pivot = 'mid')
plt.axis('equal')
plt.clim(0,0.06)
plt.gca().invert_yaxis()
```

**Comment by ShabnamR** [comment]
@alexlib Sure, that makes sense. I will use this format for quiver. Thanks! This seems to be an easy fix, but the main issue is as you mentioned the averaging process. It would be good to understand the differences in the averaging algorithm between the different versions. I have not had the time to review the two versions line by line, but I might have to do it if it cannot be fixed with simple changes. 

I have attached a zip file of 15 of the consecutive images here and also the base dockerfile I have used for creating the images. You'll only need to change the version number in the git clone lines to create different images. I have been running 0.21.8b on different sets (400 images each) of results for a few days and all capture the vortices very nicely, and all have the same issue when running the later versions. 
[Run20.zip](https://github.com/OpenPIV/openpiv-python/files/4944859/Run20.zip)

While running the experiments it is visually clear that there are 4 vortices in the plane and the center of the vortices are slightly closer to the smooth wall, but not that close that would be within the first interrogation window; so physically versions 0.21.8b and below give closer results to what is expected than the higher versions. 

Thanks for suggesting the Matlab version! I will check the Matlab version as soon as I get time.

**Comment by alexlib** [comment]
I do not see any problem. I use your `PIV_test.py` with few small modifications and I run it on two versions and get the same result. I do plot with the quiver and streamplot the `-v2` and I do `plt.gca().invert_yaxis()` to get the "visual orientation" of the vortices as they're seen by a human observer looking at the images. 

![image](https://user-images.githubusercontent.com/747110/87988492-182cc780-cae9-11ea-8881-dc8a08abe986.png)

please see the folder and the code here https://github.com/alexlib/testcase_outofplane_PIV
please note that you need to use `git lfs install` before you pull from the repository.

**Comment by ShabnamR** [comment]
That's interesting. I need to try it again with the rest of the data sets that I have. Thanks for the help!
