### ISSUE TITLE
Bias in WiDIM?

### ISSUE THREAD

**Issue by eguvep** [OpenPIV/openpiv-python#145]
Dear @alexlib,

I evaluated images using
- process.extended_search_area_piv, and
- process.WiDIM

Compared to the extended_search_area_piv, the widim result is biased to positive values. This is visible in the vector plots of the same Poiseuille-Flow:
https://github.com/OpenPIV/openpiv_tk_gui/blob/master/tst_widim/vec_extd.png
https://github.com/OpenPIV/openpiv_tk_gui/blob/master/tst_widim/vec_widim.png
As well as from the plotted velocity profiles:
https://github.com/OpenPIV/openpiv_tk_gui/blob/master/tst_widim/profile_extd.png
https://github.com/OpenPIV/openpiv_tk_gui/blob/master/tst_widim/profile_widim.png

All files necessary to reproduce the result are collected here:
https://github.com/OpenPIV/openpiv_tk_gui/tree/master/tst_widim

I used the following parameters:
a) WiDIM
overlap: 16
corr_window: 32
dt: 1.0
subpixel_method: gaussian
sig2noise_method: peak2peak
evaluation_method: widim
coarse_factor: 2

b) Extended Search Area
evaluation_method: extd_search_area
overlap: 16
corr_window: 32
dt: 1.0
subpixel_method: gaussian
sig2noise_method: peak2peak
search_area: 64

I would not expect exactly the same result, but a more random distribution of the error.

I am on Ubuntu Linux 18.04 using the OpenPivTkGui, Version 0.1.14.

**Comment by alexlib** [comment]
sorry, could you please try windef.py ? it's a different from the widim implementation and more robust.

**Comment by eguvep** [comment]
...done. It is also much faster.

**Comment by eguvep** [comment]
I found out, that it was a plotting issue, rather that a WiDIM error. WiDIM is working correctly!
