### ISSUE TITLE
preprocessing 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#149]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexlib** [comment]
see https://github.com/OpenPIV/openpiv_tk_gui/pull/19

**Comment by ErichZimmer** [comment]
Here is a simple preprocessing notebook I wrote a while ago that is incorporated in the advanced GUI. It includes spatial filters, temporal filters, and some image transformations.
https://github.com/ErichZimmer/OpenPIV_ideas/blob/main/Preprocessing_filters.ipynb

**Comment by alexlib** [comment]
@ErichZimmer please create an issue to add the functions to the preprocess.py and the notebook with the examples (while importing functions from preprocess.py) to the tutorials. It looks very interesting and clear.

**Comment by ErichZimmer** [comment]
This issue seems resolved. Should we close it?
