### ISSUE TITLE
Documentation, tutorial

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#156]
See discussion on https://groups.google.com/g/openpiv-users/c/DGR-1QC2zGM/m/PWL-dW1JAQAJ

and the answer which is the proposed TODO list:

Main documentation would be always: 
https://openpiv.readthedocs.io/en/latest/ 

We shall write it and improve it. Instead of a tutorial it now points to some notebooks 
https://openpiv.readthedocs.io/en/latest/src/tutorial.html

So the next steps would be :
1) move these notebooks to the tutorial itself under the documentation. I already know how to do it using jupyter in sphinx (here's an example using just jupyter notebooks) 

2) copy some stuff from the old tutorial https://alexlib.github.io/openpiv-python/index.html 

3) copy things from the sporadic tutorials here and there, https://github.com/OpenPIV/openpiv_basics or http://www.openpiv.net/gettingstarted.html and from all the examples: https://github.com/OpenPIV/openpiv-python/tree/master/openpiv/examples/notebooks 

Please, join me on the github (write an issue in the https://github.com/OpenPIV/openpiv-python/issues) and we will start working on it. I strongly recommend to use Jupyter noteboks - this helps both to create a single set of documentation and also an ability for the user to click and open a cloud Binder to test it with the present installation. This will also create a lot of examples one could follow. 
**Additional context**

**Comment by alexlib** [comment]
1. is ready to include jupyter notebooks in the documentation. added `nbsphinx` extension (following the `pivpy` examples) and added `tutorial1.ipynb`

**Comment by ozcanc** [comment]
Hello Alex; I see you already took action here. I am a bit lost where to start. Should/Can I start working on the item#2 above?

**Comment by alexlib** [comment]
> Hello Alex; I see you already took action here. I am a bit lost where to start. Should/Can I start working on the item#2 above?

Please start with whatever you like - any help is needed. Better I'd say if you start preparing a document that - to your best opinion - will fill the gap of PIVLab-like tutorial, answers on your own questions. This will be embedded then in the documents. 

Please follow this workflow:
1) fork this repo to your account
2) clone your repo to your local machine
2) open a new branch (better if it's on your repo so I can see the work as it goes) and update it locally. I recommend using Jupyter notebooks for this, it's easy, straightforward to reformat into Markdown or just use with the documentation. 
4) when you have some doubts, comment and ask through Github, pointing to the file or line you wonder about
5) Send a pull request to the main repo (openpiv/openpiv-python) when you think it's worth merging into the upstream/master branch. 

Thanks in advance
Alex

**Comment by ozcanc** [comment]
Hi Alex;

I think I was able to complete the steps 1-3 properly. I was able to get the installation running and now I think I am supposed to create a new Jupyter notebook and start writing a new tutorial under openpiv/docs/src. Can you please confirm?

Also I notice some broken parts in other 2 .ipynb files. Like the images are not loaded "B005_1.tif" because they do not reside in the same folder as .ipynb files. Is this intentional? 

Best regards.

**Comment by alexlib** [comment]
> Hi Alex;
> 
> I think I was able to complete the steps 1-3 properly. I was able to get the installation running and now I think I am supposed to create a new Jupyter notebook and start writing a new tutorial under openpiv/docs/src. Can you please confirm?
> 
> Also I notice some broken parts in other 2 .ipynb files. Like the images are not loaded "B005_1.tif" because they do not reside in the same folder as .ipynb files. Is this intentional?
> 
> Best regards.

Yes please, just create a notebook and move it to openpiv/doc/src

not sure about the errors - if something does not compile through sphinx - then I have to fix it.

**Comment by alexlib** [comment]
> > Hi Alex;
> > I think I was able to complete the steps 1-3 properly. I was able to get the installation running and now I think I am supposed to create a new Jupyter notebook and start writing a new tutorial under openpiv/docs/src. Can you please confirm?
> > Also I notice some broken parts in other 2 .ipynb files. Like the images are not loaded "B005_1.tif" because they do not reside in the same folder as .ipynb files. Is this intentional?
> > Best regards.
> 
> Yes please, just create a notebook and move it to openpiv/doc/src
> 
> not sure about the errors - if something does not compile through sphinx - then I have to fix it.

if you want to see the documentation on your local machine, please install `sphinx` and the packages it requires, I think the `nbsphinx` and `recommonmark`. or you can use the readthedocs.io service (that's what I do and it gives us indication if something does not compile). 
if you install locally, then `make html` from the docs/ folder creates a new folder /html and there is all the documentation.
