### ISSUE TITLE
normalize correlation map

### ISSUE THREAD

**Issue by TKaeufer** [OpenPIV/openpiv-python#158]
**Is your feature request related to a problem? Please describe.**
It is not a problem for now, but I think its required for ensemble corrleation approaches.

**Describe the solution you'd like**
I think it would be easy to realize by dividing the correlation map by it's maximum

**Comment by alexlib** [comment]
@TKaeufer I think it's already normalized in some sense - we use `normalize_intensity` before the correlation. What is the benefit of the normalized correlation? How would we then estimate `peak2peak`?

**Comment by TKaeufer** [comment]
Yes, you are right. I was about to edit the issue:

Normalized cross-correlation is something different.
https://en.wikipedia.org/wiki/Cross-correlation#Normalized_cross-correlation_(NCC)

The `normalize_intensity` function that you mentioned works somewhat similar to what the Wikipedia article says.
Eventhough the the clipping is not working as intended. Atleast from my point of view.

However, the correlation map values are exceeding the range of [-1,1] for the test I did. I think this is due to the fact that the correlation map is not divided by amount of pixel. In quickly implemented it and the results look like inteded.

>What is the benefit of the normalized correlation?

If we want to use some kind of sum-of-correlation like approach, we combine several correlation maps. By normalization, we make sure that every correlation map is weighted equally.  

> How would we then estimate peak2peak?

This should not be any problem because the peaks' relative heights should stay the same but just in the range of [0,1].

My suggestions: I rework the clipping of the normalize_intensity and and the correlation functions in a way such that i think is correct and you then have a look at them.

**Comment by alexlib** [comment]
sounds great. I am not sure if normalized cross-correlation does any better as compared to the non-normalized one. Let's see if it does. We need somewhat more objective comparison.

**Comment by alexlib** [comment]
> Yes, you are right. I was about to edit the issue:
> 
> Normalized cross-correlation is something different.
> https://en.wikipedia.org/wiki/Cross-correlation#Normalized_cross-correlation_(NCC)
> 
> The `normalize_intensity` function that you mentioned works somewhat similar to what the Wikipedia article says.
> Eventhough the the clipping is not working as intended. Atleast from my point of view.
> 
> However, the correlation map values are exceeding the range of [-1,1] for the test I did. I think this is due to the fact that the correlation map is not divided by amount of pixel. In quickly implemented it and the results look like inteded.
> 
> > What is the benefit of the normalized correlation?
> 
> If we want to use some kind of sum-of-correlation like approach, we combine several correlation maps. By normalization, we make sure that every correlation map is weighted equally.
> 
> > How would we then estimate peak2peak?
> 
> This should not be any problem because the peaks' relative heights should stay the same but just in the range of [0,1].
> 
> My suggestions: I rework the clipping of the normalize_intensity and the correlation functions in a way such that i think is correct and you then have a look at them.

if the only difference is the division by `n`, then, of course, it should not affect the position of the peak or the relative height of the two peaks. It does has some advantage, at least in principle, when we'll want to make some ensemble or average correlation and will also change the size of the window or compare the correlation with and without extended search area. In any case, the effect will be probably minor.

**Comment by TKaeufer** [comment]
I think i got it working as it should now.  Should I start a new pull request or just add it to the refactoring one? I will further describe my approach once you have acces to the code.

**Comment by alexlib** [comment]
> I think i got it working as it should now.  Should I start a new pull request or just add it to the refactoring one? I will further describe my approach once you have acces to the code.
> 
> 

Please make pull request to the windef_refactoring branch

**Comment by alexlib** [comment]
Merged in 0.23.1 see #165
