### ISSUE TITLE
TypeError: get_coordinates() got an unexpected keyword argument 'search_area_size'

### ISSUE THREAD

**Issue by barbeti** [OpenPIV/openpiv-python#168]
**Dear everyone, I have tried to follow the tutorial 1 described in** https://nbviewer.jupyter.org/github/OpenPIV/openpiv-python/blob/master/openpiv/examples/notebooks/tutorial1.ipynb taking two other personal PNG photos or the original photos.

**When I execute the following lines of codes:**

> from openpiv import tools, pyprocess, validation, filters, scaling, `process`
> from openpiv import tools, pyprocess, validation, filters, scaling, process
> 
> import numpy as np
> import matplotlib.pyplot as plt
> #matplotlib inline
> 
> import imageio
> 
> frame_a  = tools.imread( '/home/timothee/ownCloud/Thèse_UPVD-BGU/Outils_théoriques/Modeling the flow within the solar reactor/Captures_Exp_36/1.png' )
> frame_b  = tools.imread( '/home/timothee/ownCloud/Thèse_UPVD-BGU/Outils_théoriques/Modeling the flow within the solar reactor/Captures_Exp_36/1,5.png' )
> 
> fig,ax = plt.subplots(1,2,figsize=(12,10))
> ax[0].imshow(frame_a,cmap=plt.cm.gray)
> ax[1].imshow(frame_b,cmap=plt.cm.gray)
> 
> winsize = 32 # pixels, interrogation window size in frame A
> searchsize = 38  # pixels, search in image B
> overlap = 12 # pixels, 50% overlap
> dt = 0.02 # sec, time interval between pulses
> 
> u0, v0, sig2noise = pyprocess.extended_search_area_piv(frame_a.astype(np.int32), frame_b.astype(np.int32), window_size=winsize, overlap=overlap, dt=dt, search_area_size=searchsize, sig2noise_method='peak2peak')
> 
> x, y = pyprocess.get_coordinates( image_size=frame_a.shape, 
>                                  search_area_size=searchsize, 
>                                  overlap=overlap )

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**I obtain that :**
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

> File "/home/timothee/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "/home/timothee/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "/home/timothee/ownCloud/Thèse_UPVD-BGU/Simulations/PIV/Test1.py", line 33, in <module>
>     overlap=overlap )
> 
> TypeError: get_coordinates() got an unexpected keyword argument 'search_area_size'

**I am using Spyder, the python IDE available from anaconda navigator.
I am currently working from ubuntu 18.04 LTS.**

**If I execute the preceeding code with a simple command line :**
>python3 Test1.py

**I obtain the same error message :** 

> TypeError: get_coordinates() got an unexpected keyword argument 'search_area_size'

By advance thanks - Tim

**Comment by alexlib** [comment]
@barbeti please report which version do you use? we announced yesterday the 0.23.1 that probably fixed this mismatch between the tutorials and the code. 
see #165

**Comment by alexlib** [comment]
I tested now with binder 
https://mybinder.org/v2/gh/OpenPIV/openpiv-python/3093b95706f50f98d3d145cbe986753e9d009a7b

and it works without errors for 0.23.1

**Comment by barbeti** [comment]
I was using 23.0 version of openpiv-python.
Many thanks for the update.
