### ISSUE TITLE
Strange results with multipass_img_deform

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv-python#179]
**Describe the bug**
When testing OpenPIV version 0.23, there seems to be a performance issue with the `multipass_img_deform` algorithm in `windef.py`. The `first_pass` algorithm usually performs better than OpenPIV versions 0.22 and less, so the issue is not located there. As soon as the `multipass_img_deform` algorithm is used, the vector field becomes quite skewed. When using zero padding, the situation gets worse. When utilizing three passes, the situation gets much better, but some precision is lost.

**To Reproduce**
1. download PIV Challenge 2001 case A-C and E (case A shows the greatest difference)
2.  windowing set to 32px for single pass, 64>32 and 128>64>32 for multipass, all with 50% overlap
3. all settings are stock (except for windowing) on windef script for both 0.22 and 0.23 versions
4. plot results in jupyter notebook session and see differences

**Expected behavior**
The expected behavior is to see an increase in clarity as more passes are utilized. Instead, all clarity is lost as soon as the `multipass_img_deform` algorithm is used. For example, a quick comparison of a single pass ang two pass evaluation can be seen below using OpenPIV version 0.23.1.

![2001A_case_1](https://user-images.githubusercontent.com/69478071/102738341-73b8e680-430f-11eb-8f4a-6c4c942ad4e5.png)

![2001A_case_2](https://user-images.githubusercontent.com/69478071/102738362-829f9900-430f-11eb-86c1-2aa69e0ff57d.png)

![2001A_case_3](https://user-images.githubusercontent.com/69478071/102738372-8a5f3d80-430f-11eb-8e3a-c771afd68ee8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - OpenPIV Version 0.23.1 and 0.22.??

**Additional content out of context**
OpenPIV version 0.23 is noticeably slower, albeit not by too much. A quick-ish test can bee seen below where each PIV Challenge case was ran 5 times with windowing of 64>32>16 and averaged to compare the speed in milliseconds per vector.

![old_and_new_version_comparison](https://user-images.githubusercontent.com/69478071/102738516-fb9ef080-430f-11eb-81cb-dc7d195af014.png)
 
Regards,
Erich Zimmer

PS, sorry if this comes out weird as I am in a rush to get this done. Hopefully, I'll be able to do more testing and get more in depth.

**Comment by alexlib** [comment]
Please upload the notebook for the test to /examples or to gist 

Thanks for testing. Trying to find out the problems

**Comment by alexlib** [comment]
struggling with it here: https://github.com/alexlib/openpiv-python/tree/windef_noisy

**Comment by ErichZimmer** [comment]
Dear Alex,

I am pretty sure linear correlation is broken too as I keep getting crazy results. Additionally, I'll be checking the deformation algorithm as something strange is going on with `multipass_img_deform`. I did most testing with circular correlation, as it is nearly identical to the original `windef` version, and currently produces the best results.

Regards,
Erich Zimmer

**Comment by alexlib** [comment]
> Dear Alex,
> 
> 
> 
> I am pretty sure linear correlation is broken too as I keep getting crazy results. Additionally, I'll be checking the deformation algorithm as something strange is going on with `multipass_img_deform`. I did most testing with circular correlation, as it is nearly identical to the original `windef` version, and currently produces the best results. I'll have to look at it tomorrow when I get time.
> 
> 
> 
> Regards,
> 
> Erich Zimmer

Linear correlation is working ONLY with the normalized correlation option. Please check.

**Comment by ErichZimmer** [comment]
Dear Alex,

I performed a quick test with normalized correlation and the results were MUCH better. However, it still struggles with out-of-plain motion like in PIV Challenge 2001 case A. For that situation, single pass circular correlation performs the best (for OpenPIV 0.23.3). Tomorrow, I'll check what makes the newer version behave so differently compared to the previous 0.22 versions.

Regards,
Erich Zimmer

**Comment by alexlib** [comment]
I believe this is resolved in 0.23.4 version
