### ISSUE TITLE
Is there a way to cancel out unwanted regions to study? 

### ISSUE THREAD

**Issue by laChinaBarajas** [OpenPIV/openpiv-python#182]
I would like to know if there is a way to cancel areas of an image that I do not want to work with. Do not cut the image. For example a reflection of light in glass or the blades of an axis.

I have this image which I want to delimit areas where I work, the black zone and the exe with the blades. and the whole area around the cylinder

![Captura de Pantalla 2020-12-23 a la(s) 10 49 59](https://user-images.githubusercontent.com/53546388/103019596-babffb00-450c-11eb-86a3-0a3c96d54007.png)

This is an example of how I would like it to be and the results I would like to have.

![Captura de Pantalla 2020-12-23 a la(s) 10 48 51](https://user-images.githubusercontent.com/53546388/103020105-8436b000-450d-11eb-9db8-1993a070557e.png)

I tried crop the region of interest many times, but the results is not good, shows nothing. All the work I have done has been based on the examples that you have given to the community. 

So, if there is a way to obtain a similar result and do it for not only a couple of images, but to do it for a limited number greater than two.
I'd appreciate your help.

**Comment by alexlib** [comment]
@eguvep - do we have the manual image mask marker in the GUI? 


> I would like to know if there is a way to cancel areas of an image that I do not want to work with. Do not cut the image. For example a reflection of light in glass or the blades of an axis.
> 
> I have this image which I want to delimit areas where I work, the black zone and the exe with the blades. and the whole area around the cylinder
> 
> ![Captura de Pantalla 2020-12-23 a la(s) 10 49 59](https://user-images.githubusercontent.com/53546388/103019596-babffb00-450c-11eb-86a3-0a3c96d54007.png)
> 
> This is an example of how I would like it to be and the results I would like to have.
> 
> ![Captura de Pantalla 2020-12-23 a la(s) 10 48 51](https://user-images.githubusercontent.com/53546388/103020105-8436b000-450d-11eb-9db8-1993a070557e.png)
> 
> I tried crop the region of interest many times, but the results is not good, shows nothing. All the work I have done has been based on the examples that you have given to the community.
> 
> So, if there is a way to obtain a similar result and do it for not only a couple of images, but to do it for a limited number greater than two.
> I'd appreciate your help.

It seems an interesting problem. I understand that the rotor moves and then every image pair looks different, right? Could you please show us few more images that you want to mask out?

**Comment by eguvep** [comment]
Hi! 

No. At the moment, only a rectangular region of interest (ROI) can be specified in the GUI.

A static background may be treated as shown here: 
https://eguvep.github.io/jpiv/howto.html#preProcessing
This can be done with the OpenPIV Tk-GUI, but also (and possibly more flexible) with any other image processing tool, like ImageJ, for example.

But this is rather not the problem here, if I understand correctly? You have a moving background? I once evaluated PIV measurements with moving walls:
https://doi.org/10.1016/j.jbiomech.2005.03.015
I did not use manually defined masks, that would have been too tedious for hundreds of images, but I filtered the thrash vectors after evaluating the images. I used the algorithms published from that code line on:
https://github.com/eguvep/jpiv/blob/a02613d8409556feb0bf92689aca91703bb03a32/src/jpiv2/PivData.java#L1342

However, this algorithm is very special and relies on the no slip condition on the wall. It certainly must be adapted for your cases.

Regards!

Peter

**Comment by alexlib** [comment]
https://github.com/laChinaBarajas - is it a static or dynamic image?

**Comment by ErichZimmer** [comment]
Dear Alex, Peter, and @laChinaBarajas ,

I am working to update the OpenPIV tk GUI with manual and algorithmic object masking. All appears to be fine until a region of interest is applied as the masked vectors are not repositioned (don't know why).

masks with mask object:
![PIV_Challenge_2014B_mask_test](https://user-images.githubusercontent.com/69478071/103467842-d69b7c00-4d18-11eb-806e-1a71a5b30153.png)

mask with mask object disabled:
![mask_works_first_time](https://user-images.githubusercontent.com/69478071/103467848-eb780f80-4d18-11eb-9a7b-54936cee680c.png)

Bug encounter when using ROI and masks:
![bug_5](https://user-images.githubusercontent.com/69478071/103467951-dbacfb00-4d19-11eb-92e1-86c23ef0fdfb.JPG)

Please keep in mind that this is practically a new GUI based off of the great work done by  @eguvep  and Dr. Thielicke (PIVlab). and was created about eight days ago, so many bugs are to be expected :)

Regards,
Erich Zimmer

**Comment by alexlib** [comment]
I guess, you need to check carefully that the vertical coordinate is flipped - during multi-grid we use the image-based coordinate system with 0,0 at the top left corner, and only export the "final" coordinate system before saving it. It could affect the mask location that needs to be set at each grid refinement.

**Comment by ErichZimmer** [comment]
Dear Alex,
I think it has something to do with the vectors being translated via adding the top left coordinates of the region of interest to the x and y component of the vector field. I tried to translate the masked vectors back to their original position, but that did not work as the masked vectors (marked as `x` in this case) were decoupled from the NaNs and were also not aligned with the vector field. I'll have to dig some more to see what I keep messing up on, but it will take a while as I am still a high school graduate with minimal python knowledge (just enough to contribute though :P ).

Regards,
Erich Zimmer

PS, the vector field is aligned in image-based coordinate format with the origin top left

**Comment by ErichZimmer** [comment]
I solved the issue, it was a misplaced `+` sign which made `+=` instead of `=`. The results are now exactly the same as PIVlab and PIVview.
![PIV_Challenge_2014B_mask_test](https://user-images.githubusercontent.com/69478071/103469961-57ff0880-4d31-11eb-8652-91112edd774b.png)

![fixed_bug_5](https://user-images.githubusercontent.com/69478071/103469962-60574380-4d31-11eb-92da-1e027fdc7bcc.png)

![what_is_this](https://user-images.githubusercontent.com/69478071/103470014-26d30800-4d32-11eb-8113-8378a41b5189.png)

**Comment by ErichZimmer** [comment]
I'll finish the package up in a few days and let anyone who is interested in it use it. Maybe, I'll pull request it for the original Openpiv_tk_gui, but I fear that the differences may be simply too large to merge.

**Comment by alexlib** [comment]
You're welcome to open a new branch and leave it all there. We won't merge it into master until we decide which way to go. Thanks for all the time.

**Comment by laChinaBarajas** [comment]
Hello, thanks for replying.
My images are static, obtained from a video.

> https://github.com/laChinaBarajas - is it a static or dynamic image?

**Comment by alexlib** [comment]
> Hello, thanks for replying.
> 
> My images are static, obtained from a video.
> 
> 
> 
> > https://github.com/laChinaBarajas - is it a static or dynamic image?
> 
> 
> 
> 

Sorry if I wasn't clear - the question is whether the masked region is static - is it the same region in all images or it is a moving mask?

**Comment by laChinaBarajas** [comment]
> > Hello, thanks for replying.
> > My images are static, obtained from a video.
> > > https://github.com/laChinaBarajas - is it a static or dynamic image?
> 
> Sorry if I wasn't clear - the question is whether the masked region is static - is it the same region in all images or it is a moving mask?

I have 99 images and I would like the masked region will the same for all images.

**Comment by alexlib** [comment]
> I have 99 images and I would like the masked region will the same for all images.

So it's one of the two options now: a) GUI (see @ErichZimmer remark) or b) use this notebook to create a mask using your mouse over the image clicks and then reuse the mask in the OpenPIV. 

If you upload two real images - I'll make a complete tutorial for the best use of it with the updated version of OpenPIV 0.23.4
