### ISSUE TITLE
Enable retrieval of correlation value used to estimate velocity

### ISSUE THREAD

**Issue by hcwinsemius** [OpenPIV/openpiv-python#184]
**Is your feature request related to a problem? Please describe.**
I am tracing movements of river water in OpenPIV, which works very well. However, it remains difficult to filter out spurious velocities, that are simply due to very poor correlation found between interrogation windows in frame pairs. a peak2peak or peak2mean filtering simply doesn't work, as they don't account for thresholding on poor correlation, but merely for thresholding on variability in correlation across an interrogation window (if the peak in correlation is very similar to the next peak or the average, then we filter, otherwise we keep, versus much simpler, the peak correlation is very low and therefore likely not give a trustworthy velocity vector).

**Describe the solution you'd like**
Enable extracting the correlation in the pyprocess.extended_search_area_piv method

**Describe alternatives you've considered**
I am circumventing this by calling underlying functions myself, this is however very clunky and duplication of efforts. Much neater would be to simply return the correlations or maximum correlation value along with u, v, sig2noise.

**Additional context**

**Comment by alexlib** [comment]
Hi @hcwinsemius - what do you mean by extracting the correlation? every interrogation window returns a vector of displacement and the `sig2noise` value. If you want to measure the signal to noise ratio differently, please help us to define the parameter. If you simply want to get all the correlation values - this is a bit too much for the function to return I think as it's a huge matrix. It's of course not difficult to do, but we'd rather not to do it by default. 
I suggest that you do the following: 
1) fork the repo to your account
2) create a branch for your need
3) change one-line `    return u/dt, v/dt, sig2noise` to `    return u/dt, v/dt, sig2noise, corr` in the `extended_search_area_piv` and you'll get `corr` as the 4th output, https://github.com/OpenPIV/openpiv-python/blob/13c3a6a67380c0323099ddec4d817dfcfe4e5620/openpiv/pyprocess.py#L801

You'll probalby need to loop through `corr` matrix to get maximum or whatever you want to get. Take a look at the `correlation_to_displacement` on how it's done now: https://github.com/OpenPIV/openpiv-python/blob/13c3a6a67380c0323099ddec4d817dfcfe4e5620/openpiv/pyprocess.py#L804

If you then use `corr` in some particular way, please send us here a link to your branch and we'll try to see if it's useful also to other users. 

Regards
Alex
