### ISSUE TITLE
OpenPiv Installation Problem in python3.6 in windows 10

### ISSUE THREAD

**Issue by PAMPA-1996** [OpenPIV/openpiv-python#185]
I am trying to install the openpiv in my windows10 in python3.6.
But I am unable. again again I am getting the issues. I installed all dependency packages. Can you help me to resolve this particular issue?
Here is the error.
"**Building wheels for collected packages: OpenPiv
  Building wheel for OpenPiv (PEP 517) ... error
  ERROR: Command errored out with exit status 1**:command: 'c:\users\admin\appdata\local\programs\python\python36\python.exe' 'c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Admin\AppData\Local\Temp\tmpgngzfbhk'"

**Comment by alexlib** [comment]
The compiler is probably missing. We recommend to use anaconda or miniconda installation that covers all these issues and provides binary wheels support.
