### ISSUE TITLE
improve PIV performance by using FFT from scipy

### ISSUE THREAD

**Issue by MaxBrazhnikov** [OpenPIV/openpiv-python#187]
FFT routines from scipy are more sophisticated than ones from numpy. Replacing numpy.fft with scipy.fft in pyprocess.py speeds up PIV almost twice for me.

**Comment by alexlib** [comment]
@MaxBrazhnikov - sounds great. could you please share your fork? You're welcome to run some tests and submit a pull request.

**Comment by alexlib** [comment]
My quick test on one of the example notebooks did show some time saving, but not significant. Probably it requires a deeper investigation.

**Comment by alexlib** [comment]
@MaxBrazhnikov could you please check if there is pyfftw installed on your machine? it can make the difference
https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.set_backend.html
https://stackoverflow.com/questions/62465583/scipy-fft-backends-possibilities

**Comment by alexlib** [comment]
https://stackoverflow.com/questions/64590100/pyfftw-perfomance-on-multidimensional-arrays/64606010#64606010

**Comment by MaxBrazhnikov** [comment]
> @MaxBrazhnikov - sounds great. could you please share your fork? You're welcome to run some tests and submit a pull request.

Well, I've been too optimistic. While scipy is faster than numpy on my system (see test below), overall PIV speed-up is about 25% for my setup (I run multi-pass PIV on 3000x3000px images).

import numpy as np
from scipy.fft import rfft2 as scipy_rfft2
from scipy.fft import irfft2 as scipy_irfft2
from numpy.fft import rfft2 as numpy_rfft2
from numpy.fft import irfft2 as numpy_irfft2

​N = 32
X = np.arange(0, 1, 1/N)
X, Y = np.meshgrid(X, X)
Z = np.sin(10*np.pi*X) + np.sin(10*np.pi*Y) + 0.001 * np.random.uniform(0, 1, X.shape)

%timeit scipy_irfft2(scipy_rfft2(Z) * scipy_rfft2(Z))
%timeit numpy_irfft2(numpy_rfft2(Z) * numpy_rfft2(Z))

74.8 µs ± 1.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
157 µs ± 874 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**Comment by MaxBrazhnikov** [comment]
> @MaxBrazhnikov could you please check if there is pyfftw installed on your machine? it can make the difference
> https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.set_backend.html
> https://stackoverflow.com/questions/62465583/scipy-fft-backends-possibilities

No, I don't use pyfftw.

**Comment by alexlib** [comment]
25% is not negligible, Thanks for pointing it out. May I ask you what you're doing with openpiv and whether you use the GUI or notebooks / scripts? What is the installation platform?

**Comment by alexlib** [comment]
I get similar results, the differences are not drastic, but I think it's not a major replacement as we anyhow depend on scipy.

**Comment by MaxBrazhnikov** [comment]
> 25% is not negligible, Thanks for pointing it out. May I ask you what you're doing with openpiv and whether you use the GUI or notebooks / scripts?
I use my scripts, basically wrappers around openpiv functions, for batch processing of raw data. The scripts are too specific for general use, I was looking ways to improve scripts performance and found that scipy makes difference.

> What is the installation platform?
It's FreeBSD/amd64

**Comment by alexlib** [comment]
We merged scipy.fft - see #188

**Comment by alexlib** [comment]
Thanks @MaxBrazhnikov
