### ISSUE TITLE
Unespected value using widim

### ISSUE THREAD

**Issue by Aguilar-Cabello** [OpenPIV/openpiv-python#189]
I've been using openpiv for the first time and I got some unexpected values. I generated a synthetic image where all points move 5 pixels in the x-direction. I used the single-pass example of notebook 1, and everything 
works fine. The problem is when I jump to the multi-pass example using widim. I see a weird shift on the solution vectors. I'm using this very simple call similar to the tutorial:

 x,y,u,v, mask = widim.WiDIM(frame_a.astype(np.int32),
                                frame_b.astype(np.int32),
                                ones_like(frame_a).astype(np.int32),
                                min_window_size=32,
                                overlap_ratio=0.5,
                                coarse_factor=1,
                                dt=1,
                                validation_method='mean_velocity',
                                trust_1st_iter=1,
                                validation_iter=2,
                                tolerance=0.7,
                                nb_iter_max=2,
                                sig2noise_method='peak2peak')

When I compute the results I obtain the following results on the vector field which is substantially worse than the one obtained using a single pass (I only represent some vectors to see more clearly):

![Field](https://user-images.githubusercontent.com/81618886/112971802-df50f200-914f-11eb-893a-5d391c5b31f6.png)

I'm wondering if there is something I'm doing wrong or for some reason, this method is not recommended for this simple case.

I also attach the images I used.

![constant_test_1](https://user-images.githubusercontent.com/81618886/112971884-f394ef00-914f-11eb-9943-3ad5bfd1173e.png)
![constant_test_2](https://user-images.githubusercontent.com/81618886/112971887-f42d8580-914f-11eb-857e-917ea81b0e07.png)

Thank you in advance

**Comment by TKaeufer** [comment]
@alexlib

**Comment by alexlib** [comment]
Thanks for the issue report. We need to test it. Could you please meanwhile check it with the windef? 
Thanks

**Comment by alexlib** [comment]
I confirm there is a problem @Aguilar-Cabello @TKaeufer 
I however suspect that it's an issue with the fact that all vectors are identical. 
Also in `windef` this leads to a problem in the validation step, but we resolved it there. In WiDIM it is apparently not so. 

@Aguilar-Cabello - could you please try with a synthetic image that is not all the same shift, but with some random noise or variability?

@Aguilar-Cabello - which synthetic image generator do you use?

**Comment by Aguilar-Cabello** [comment]
Thank you for the reply.

@alexlib - I've tested using window deformation and it works fine

@alexlib  - I've tested with a triangular random noise on velocity of 2 pixels centered in 0 to generate the images. The PIV output is similar and the problem persists. 

@alexlib - I'm using my own custom script to generate the images.

**Comment by alexlib** [comment]
> 
> 
> Thank you for the reply.
> 
> @alexlib - I've tested using window deformation and it works fine

 @Aguilar-Cabello  if `windef.py` works fine, we won't try to fix `widim.pyx`. In any case, we decided to retire this old and buggy version. 
> 
> @alexlib - I've tested with a triangular random noise on velocity of 2 pixels centered in 0 to generate the images. The PIV output is similar and the problem persists.

@Aguilar-Cabello  if the problem persists with `windef.py` then it means we have some issue with the `validation.py` - I'd need to dig deeper. Please share your images with the noise and I'll make a test on them. 


> 
> @alexlib - I'm using my own custom script to generate the images.

@Aguilar-Cabello If it's in Python - would you be willing to contribute it to the community? We have one synthetic image generator in the code, but we do not use it often and not sure about its robustness and computational load.

**Comment by Aguilar-Cabello** [comment]
@alexlib The problem only appears on windim in both cases (constant velocity and constant+random noise), windef works fine in both cases. 

I would like to contribute. Unfortunately, I don't have time these days to properly work on it, but I plan to share it in close future.
