### ISSUE TITLE
Suggest to retire the widim.pyx 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#190]
widim.pyx has bugs, see #189, maybe it's not in all cases, but in some cases, but it's a fact. See also previous complains:
https://github.com/OpenPIV/openpiv-python/search?q=widim&type=issues
 The original developer is not active anymore and we do not use Cython for anything else. So, there is no one that can basically debug it properly or support it. Removing Cython will also make installation smoother as we will remove Cython and also compiler requirements. We'll be a `pure` Python package based on numpy, scipy, matplotlib, scikit-image, imageio 

**Describe the solution you'd like**
I suggest to remove `widim.pyx` from the openpiv-python repository

**Describe alternatives you've considered**
Open a feature issue requesting somebody who knows Cython and OpenPIV to jump in and debug it.

**Comment by eguvep** [comment]
We removed widim already from the GUI. From this point of view, there is no problem with removing widim.

**Comment by TKaeufer** [comment]
I agree, the functionality is already covered and extended by windef. Let's remove it.

**Comment by alexlib** [comment]
removed, from 0.23.5 and on
