### ISSUE TITLE
Link to Tutorial Notebook 2 is broken

### ISSUE THREAD

**Issue by gui-miotto** [OpenPIV/openpiv-python#198]
Link to Tutorial notebook 2 resolves to error 404.

**Comment by alexlib** [comment]
thanks @gui-miotto for noticing. the `tutorial2.ipynb` was missing and I created it. but there is some issue with the nbviewer that I cannot fix and it does not relate to the notebook as Github renders it well 

https://github.com/OpenPIV/openpiv-python/blob/master/openpiv/examples/notebooks/tutorial2.ipynb

**Comment by alexlib** [comment]
for instance, their own examples do not work 
https://nbviewer.jupyter.org/url/jakevdp.github.com/downloads/notebooks/XKCD_plots.ipynb
