### ISSUE TITLE
Should we add a "dont_display" argument to the display_vector_field function?

### ISSUE THREAD

**Issue by gui-miotto** [OpenPIV/openpiv-python#203]
This would be useful for saving the fields as images on the hard drive, instead of looking at them at execution time. 
That is, by the way, my current usage. Every time I run my code, it produces hundreds of these maps in the hard drive. To do that, I had to comment out line 142 of tools.py: 

https://github.com/OpenPIV/openpiv-python/blob/f71ddb8ae410d9dff5c31d48d98f528fbd37e3f7/openpiv/tools.py#L139-L145

Needles to say, the `dont_display` argument would default to `False`. 
Let me know what you think.
I could prepare the PR.

Best,
GM

**Comment by alexlib** [comment]
It's a good idea, @gui-miotto, but could you please articulate better the need? Our workflow is slightly different, I guess. What we do usually is to use on-the-fly display only for a very small, interactive part of the analysis. Then, the batch run of many image pairs is done without any display and only the .vec files are saved on the drive. The next step is the post-processing one and it's very rare that we need an animation of the flow of keeping a large number of images with arrows on them. But, if we need it, there is a PIVPy https://github.com/OpenPIV/pivpy that we slowly develop or a GUI https://github.com/OpenPIV/openpiv_tk_gui that take care of this part. 
If you explain why would we want to use `display_vector_field` without actual display (paradox :)), of course, let's take a step. The implementation is definitely not that difficult, but I think we could suggest to the users a better workflow pattern.
