### ISSUE TITLE
Error in OpenPIV due to images

### ISSUE THREAD

**Issue by BrouwersBart** [OpenPIV/openpiv-python#228]
Hi,

I have two sets of images both representing a flow in non-transparent mud fluid.

The two sets of images are generated using ultrasound transducers at a frequency of 5 MHz and 3.5 MHz. Because of this difference in ultrasound frequency, the operating systems controlling the two transducers were different. Despite this difference we paid great attention in generating images with similar properties (16 bit, grayscale, tiff, ….). Only the size of the images, which is related to the dimensions of the arrays, remain different.
 
Nonetheless, when processing these images with OpenPIV the first set of images (5 MHz) give nice results, while the processing of the second set of images (3.5 MHz) results in an error:
![image](https://user-images.githubusercontent.com/95429618/144450968-e2797f37-efda-4954-bd7e-fd1c2a00dd6d.png)

As the script works fine with the first set of images and not with the second, I presume the error is related to the images. I have however no idea anymore what could be the issue. As mentioned earlier, apart from the size the image properties look the same for me.
Nonetheless I also tried amending the shape of the second set of images, by cropping them to square shapes (x = y) instead of the original elongated rectangle shapes (x <<< y). This resulted in a similar error, with only a change in the last line:
 
(my>ky) failed for hidden my: regrid_smth:my=2
became 
(m**x**>k**x**) failed for hidden m**x**: regrid_smth:m**x**=2
 
This makes me doubt if the issue might indeed be the different sizing of the images.
 
Anyhow I am really out of ideas and wonder if someone could help me with this. An explanation of the meaning of the error would already be very helpful.
 
On a sidenote, I use a customized version of OpenPIV, which is modified starting from your OpenPIV version 0.22.3. 

Hereby I attach
- Set 1 of images (5 MHz) + generated OpenPIV results
- Set 2 of images (3.5 MHz)
- OpenPIV script used

[Files BBS.zip](https://github.com/OpenPIV/openpiv-python/files/7643085/Files.BBS.zip)

Thanks in advance for any help at all :-)

**Comment by ErichZimmer** [comment]
Your interrogation windows are too large for your 3.5MHz images. Please try to keep at least three interrogation windows in each axes.

**Comment by ErichZimmer** [comment]
E.g. 40x40>40x40>20x20px windows with 50% overlap.

**Comment by BrouwersBart** [comment]
Thank you for this fast response. 
Smaller interrogation windows indeed resolve the issue, which makes perfect sense.  I guess I've been dozing off too long that I did have a clear view anymore :-).
