### ISSUE TITLE
One program error in the document.

### ISSUE THREAD

**Issue by WK-Luo** [OpenPIV/openpiv-python#231]
I found an error on the "Basics of Particle Image Velocimetry (PIV)" page, as shown in the code attached. I guess that is because the program runs every time people open the page, and the picture was deleted. Or just save the wrong version. Although it's a tiny mistake, it can still confuse beginners. 
[https://openpiv.readthedocs.io/en/latest/src/piv_basics.html](url)

<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[2]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre><span></span><span class="c1"># load the images:</span>
<span class="n">a</span> <span class="o">=</span> <span class="n">imread</span><span class="p">(</span><span class="s1">'B005_1.tif'</span><span class="p">)</span>
<span class="n">b</span> <span class="o">=</span> <span class="n">imread</span><span class="p">(</span><span class="s1">'B005_2.tif'</span><span class="p">)</span>

<span class="n">figure</span><span class="p">(</span><span class="n">figsize</span><span class="o">=</span><span class="p">(</span><span class="mi">12</span><span class="p">,</span><span class="mi">10</span><span class="p">))</span>
<span class="n">subplot</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span><span class="mi">2</span><span class="p">,</span><span class="mi">1</span><span class="p">)</span>
<span class="n">imshow</span><span class="p">(</span><span class="n">a</span><span class="p">,</span><span class="n">cmap</span><span class="o">=</span><span class="n">cm</span><span class="o">.</span><span class="n">gray</span><span class="p">)</span>
<span class="n">subplot</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span><span class="mi">2</span><span class="p">,</span><span class="mi">2</span><span class="p">)</span>
<span class="n">imshow</span><span class="p">(</span><span class="n">b</span><span class="p">,</span><span class="n">cmap</span><span class="o">=</span><span class="n">cm</span><span class="o">.</span><span class="n">gray</span><span class="p">)</span>
<span class="c1"># imshow(c_[a,b],cmap=cm.gray)</span>
</pre></div>
</div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre><span class="ansi-red-fg">---------------------------------------------------------------------------</span>
<span class="ansi-red-fg">FileNotFoundError</span>                         Traceback (most recent call last)
<span class="ansi-green-fg">&lt;ipython-input-2-652973821a4e&gt;</span> in <span class="ansi-cyan-fg">&lt;module&gt;</span>
<span class="ansi-green-intense-fg ansi-bold">      1</span> <span class="ansi-red-fg"># load the images:</span>
<span class="ansi-green-fg">----&gt; 2</span><span class="ansi-red-fg"> </span>a <span class="ansi-blue-fg">=</span> imread<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">'B005_1.tif'</span><span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">      3</span> b <span class="ansi-blue-fg">=</span> imread<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">'B005_2.tif'</span><span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">      4</span>
<span class="ansi-green-intense-fg ansi-bold">      5</span> figure<span class="ansi-blue-fg">(</span>figsize<span class="ansi-blue-fg">=</span><span class="ansi-blue-fg">(</span><span class="ansi-cyan-fg">12</span><span class="ansi-blue-fg">,</span><span class="ansi-cyan-fg">10</span><span class="ansi-blue-fg">)</span><span class="ansi-blue-fg">)</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/skimage/io/_io.py</span> in <span class="ansi-cyan-fg">imread</span><span class="ansi-blue-fg">(fname, as_gray, plugin, **plugin_args)</span>
<span class="ansi-green-intense-fg ansi-bold">     46</span>
<span class="ansi-green-intense-fg ansi-bold">     47</span>     <span class="ansi-green-fg">with</span> file_or_url_context<span class="ansi-blue-fg">(</span>fname<span class="ansi-blue-fg">)</span> <span class="ansi-green-fg">as</span> fname<span class="ansi-blue-fg">:</span>
<span class="ansi-green-fg">---&gt; 48</span><span class="ansi-red-fg">         </span>img <span class="ansi-blue-fg">=</span> call_plugin<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">'imread'</span><span class="ansi-blue-fg">,</span> fname<span class="ansi-blue-fg">,</span> plugin<span class="ansi-blue-fg">=</span>plugin<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">**</span>plugin_args<span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">     49</span>
<span class="ansi-green-intense-fg ansi-bold">     50</span>     <span class="ansi-green-fg">if</span> <span class="ansi-green-fg">not</span> hasattr<span class="ansi-blue-fg">(</span>img<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">'ndim'</span><span class="ansi-blue-fg">)</span><span class="ansi-blue-fg">:</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/skimage/io/manage_plugins.py</span> in <span class="ansi-cyan-fg">call_plugin</span><span class="ansi-blue-fg">(kind, *args, **kwargs)</span>
<span class="ansi-green-intense-fg ansi-bold">    205</span>                                (plugin, kind))
<span class="ansi-green-intense-fg ansi-bold">    206</span>
<span class="ansi-green-fg">--&gt; 207</span><span class="ansi-red-fg">     </span><span class="ansi-green-fg">return</span> func<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">*</span>args<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">**</span>kwargs<span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">    208</span>
<span class="ansi-green-intense-fg ansi-bold">    209</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/skimage/io/_plugins/tifffile_plugin.py</span> in <span class="ansi-cyan-fg">imread</span><span class="ansi-blue-fg">(fname, **kwargs)</span>
<span class="ansi-green-intense-fg ansi-bold">     28</span>         kwargs<span class="ansi-blue-fg">[</span><span class="ansi-blue-fg">'key'</span><span class="ansi-blue-fg">]</span> <span class="ansi-blue-fg">=</span> kwargs<span class="ansi-blue-fg">.</span>pop<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">'img_num'</span><span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">     29</span>
<span class="ansi-green-fg">---&gt; 30</span><span class="ansi-red-fg">     </span><span class="ansi-green-fg">return</span> tifffile_imread<span class="ansi-blue-fg">(</span>fname<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">**</span>kwargs<span class="ansi-blue-fg">)</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/tifffile/tifffile.py</span> in <span class="ansi-cyan-fg">imread</span><span class="ansi-blue-fg">(files, aszarr, **kwargs)</span>
<span class="ansi-green-intense-fg ansi-bold">    779</span>
<span class="ansi-green-intense-fg ansi-bold">    780</span>         <span class="ansi-green-fg">if</span> isinstance<span class="ansi-blue-fg">(</span>files<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">(</span>str<span class="ansi-blue-fg">,</span> os<span class="ansi-blue-fg">.</span>PathLike<span class="ansi-blue-fg">)</span><span class="ansi-blue-fg">)</span> <span class="ansi-green-fg">or</span> hasattr<span class="ansi-blue-fg">(</span>files<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">'seek'</span><span class="ansi-blue-fg">)</span><span class="ansi-blue-fg">:</span>
<span class="ansi-green-fg">--&gt; 781</span><span class="ansi-red-fg">             </span><span class="ansi-green-fg">with</span> TiffFile<span class="ansi-blue-fg">(</span>files<span class="ansi-blue-fg">,</span> <span class="ansi-blue-fg">**</span>kwargs_file<span class="ansi-blue-fg">)</span> <span class="ansi-green-fg">as</span> tif<span class="ansi-blue-fg">:</span>
<span class="ansi-green-intense-fg ansi-bold">    782</span>                 <span class="ansi-green-fg">if</span> aszarr<span class="ansi-blue-fg">:</span>
<span class="ansi-green-intense-fg ansi-bold">    783</span>                     <span class="ansi-green-fg">return</span> tif<span class="ansi-blue-fg">.</span>aszarr<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">**</span>kwargs<span class="ansi-blue-fg">)</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/tifffile/tifffile.py</span> in <span class="ansi-cyan-fg">__init__</span><span class="ansi-blue-fg">(self, arg, mode, name, offset, size, _multifile, _useframes, _master, **kwargs)</span>
<span class="ansi-green-intense-fg ansi-bold">   2895</span>             <span class="ansi-green-fg">raise</span> ValueError<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">f'invalid mode {mode!r}'</span><span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">   2896</span>
<span class="ansi-green-fg">-&gt; 2897</span><span class="ansi-red-fg">         </span>fh <span class="ansi-blue-fg">=</span> FileHandle<span class="ansi-blue-fg">(</span>arg<span class="ansi-blue-fg">,</span> mode<span class="ansi-blue-fg">=</span>mode<span class="ansi-blue-fg">,</span> name<span class="ansi-blue-fg">=</span>name<span class="ansi-blue-fg">,</span> offset<span class="ansi-blue-fg">=</span>offset<span class="ansi-blue-fg">,</span> size<span class="ansi-blue-fg">=</span>size<span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">   2898</span>         self<span class="ansi-blue-fg">.</span>_fh <span class="ansi-blue-fg">=</span> fh
<span class="ansi-green-intense-fg ansi-bold">   2899</span>         self<span class="ansi-blue-fg">.</span>_multifile <span class="ansi-blue-fg">=</span> bool<span class="ansi-blue-fg">(</span>_multifile<span class="ansi-blue-fg">)</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/tifffile/tifffile.py</span> in <span class="ansi-cyan-fg">__init__</span><span class="ansi-blue-fg">(self, file, mode, name, offset, size)</span>
<span class="ansi-green-intense-fg ansi-bold">   9207</span>         self<span class="ansi-blue-fg">.</span>is_file <span class="ansi-blue-fg">=</span> <span class="ansi-green-fg">None</span>
<span class="ansi-green-intense-fg ansi-bold">   9208</span>         self<span class="ansi-blue-fg">.</span>_lock <span class="ansi-blue-fg">=</span> NullContext<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">)</span>
<span class="ansi-green-fg">-&gt; 9209</span><span class="ansi-red-fg">         </span>self<span class="ansi-blue-fg">.</span>open<span class="ansi-blue-fg">(</span><span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">   9210</span>
<span class="ansi-green-intense-fg ansi-bold">   9211</span>     <span class="ansi-green-fg">def</span> open<span class="ansi-blue-fg">(</span>self<span class="ansi-blue-fg">)</span><span class="ansi-blue-fg">:</span>

<span class="ansi-green-fg">~/miniconda3/envs/openpiv/lib/python3.7/site-packages/tifffile/tifffile.py</span> in <span class="ansi-cyan-fg">open</span><span class="ansi-blue-fg">(self)</span>
<span class="ansi-green-intense-fg ansi-bold">   9220</span>             self<span class="ansi-blue-fg">.</span>_file <span class="ansi-blue-fg">=</span> os<span class="ansi-blue-fg">.</span>path<span class="ansi-blue-fg">.</span>realpath<span class="ansi-blue-fg">(</span>self<span class="ansi-blue-fg">.</span>_file<span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">   9221</span>             self<span class="ansi-blue-fg">.</span>_dir<span class="ansi-blue-fg">,</span> self<span class="ansi-blue-fg">.</span>_name <span class="ansi-blue-fg">=</span> os<span class="ansi-blue-fg">.</span>path<span class="ansi-blue-fg">.</span>split<span class="ansi-blue-fg">(</span>self<span class="ansi-blue-fg">.</span>_file<span class="ansi-blue-fg">)</span>
<span class="ansi-green-fg">-&gt; 9222</span><span class="ansi-red-fg">             </span>self<span class="ansi-blue-fg">.</span>_fh <span class="ansi-blue-fg">=</span> open<span class="ansi-blue-fg">(</span>self<span class="ansi-blue-fg">.</span>_file<span class="ansi-blue-fg">,</span> self<span class="ansi-blue-fg">.</span>_mode<span class="ansi-blue-fg">)</span>
<span class="ansi-green-intense-fg ansi-bold">   9223</span>             self<span class="ansi-blue-fg">.</span>_close <span class="ansi-blue-fg">=</span> <span class="ansi-green-fg">True</span>
<span class="ansi-green-intense-fg ansi-bold">   9224</span>             <span class="ansi-green-fg">if</span> self<span class="ansi-blue-fg">.</span>_offset <span class="ansi-green-fg">is</span> <span class="ansi-green-fg">None</span><span class="ansi-blue-fg">:</span>

<span class="ansi-red-fg">FileNotFoundError</span>: [Errno 2] No such file or directory: '/home/user/Downloads/repos/openpiv-python/openpiv/docs/src/B005_1.tif'
</pre></div></div>
</div>

**Comment by alexlib** [comment]
These images exist - but as the document proposes the user has to download them:

[http://www.pivchallenge.org/pub/B/B005_1.tif](http://www.pivchallenge.org/pub/B/B005_1.tif)
[http://www.pivchallenge.org/pub/B/B005_1.tif](http://www.pivchallenge.org/pub/B/B005_1.tif) 

The notebook rendered properly on the github

**Comment by alexlib** [comment]
thanks @WK-Luo it's resolved now.
