### ISSUE TITLE
How to evaluate Image quality for OpenPIV use

### ISSUE THREAD

**Issue by BrouwersBart** [OpenPIV/openpiv-python#233]
Dear OpenPIV community,

I am trying to visualize and measure flow velocities in cohesive sediments (mud) using OpenPIV, based on speckle pattern images created using an ultrasound scanner.

Typical pair of images are enclosed, together with the OpenPIV output on this pair:
![A006b](https://user-images.githubusercontent.com/95429618/157407025-d692c005-9fcc-41aa-9adf-bd759f49a9c7.jpg)
![A006a](https://user-images.githubusercontent.com/95429618/157407028-343b94cd-7526-4e9b-9702-0382eb4304e2.jpg)
[field_06.txt](https://github.com/OpenPIV/openpiv-python/files/8213233/field_06.txt)
![Field06](https://user-images.githubusercontent.com/95429618/157408967-828354ab-9f5d-4920-8d7f-1dbe9d194820.png)

As you can see the pixel brightness decreases with increasing depth due to attenuation of the ultrasound radiation in the mud. While penetration depth can be enhanced by decreasing the ultrasound frequency, the speckle brightness also decreases with decreasing frequency. At a certain depth or lower frequency the quality of the speckles will thus be insufficient for processing with OpenPIV and therefore leads to a trade-off between penetration depth and speckle brightness.

In order to find the optimal ultrasound frequency I performed a lot of tests using different ultrasound frequencies. The idea was to process all the images for each setup using OpenPIV in order to find the depth till which Vectors are generated, meaning speckle intensity is still sufficient.

I am however struggling in finding the correct way to evaluate this. The idea was to see at which depth vectors become masked. For the examples attached this would be around 30 mm depth. 

This however strongly depends on the settings for validation. So I start to ask myself:
- Which validation should I use (S2N, max displacement, std,  median, ....)
- Should I use only one or a combination? 
- For the example above I used all. The question is then which one is critical?
- Should my validation thresholds be the same for all tests or should I be flexible with this?

Does any one have experience with a similar exercise and can advise on how to tackle this?

Thanks in advance.

**Comment by alexlib** [comment]
@BrouwersBart This sounds like a complex problem that is not so much related to PIV. E.g. one could run a brightness correction scheme to get more brightness and different region of analysis. This however will only add noise at the places where the image is not related to the speckles and therefore "not moving". 
I'm not sure about "validation" - the fact that we get a vector (right or wrong one) has not so much to deal with the image itself. we already had places where the vectors were "okay" but it was an artifact.

**Comment by alexlib** [comment]
@BrouwersBart please send your question to the forum - maybe somebody had more experience with it. 
https://groups.google.com/g/openpiv-users?pli=1

btw, could you point us to the explanation of how the experiment is done?

**Comment by BrouwersBart** [comment]
I used the old school trial and error method to resolve this issue. By playing with each validation parameter seperately I was able to find a threshold at which the output was optimal. Quiet a lot of work, but the result was satisfying.
