### ISSUE TITLE
Add Sphinx for documentation 

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv-python#242]
**Is your feature request related to a problem? Please describe.**
Currently, documentation for individual functions is lacking, and adding them manually is too labor intensive.

**Describe the solution you'd like**
Use Sphinx to automatically build documentation (like [openpivgui](https://github.com/OpenPIV/openpiv_tk_gui/tree/master/docs))

**Describe alternatives you've considered**
Manually add documentation?

**Comment by alexlib** [comment]
what has to be extended in the docs folder ? https://github.com/OpenPIV/openpiv-python/tree/master/openpiv/docs

**Comment by ErichZimmer** [comment]
I would like to have an API reference added to the docs, as currently, there is none from what I can see.
https://openpiv.readthedocs.io/en/latest/src/api_reference.html

**Comment by alexlib** [comment]
yes, there's something with the sphinx configurations that I do not know much about.

**Comment by alexlib** [comment]
we also include 
```
.. automodule:: openpiv.preprocess
    :members:
```
but it does not create these. I need to run Sphinx locally to understand what's necessary here. If you have some time to look into it, please do

**Comment by alexlib** [comment]
ok, when I run it locally, it generates the documentation as it's supposed to be. i need to check what's wrong with the readthedocs log

**Comment by alexlib** [comment]
found it - 
https://readthedocs.org/api/v2/build/17162054.txt

shows that we get 
`WARNING: autodoc: failed to import module 'preprocess' from module 'openpiv'; the following exception was raised:
No module named 'openpiv'`

need to check what's required there

**Comment by alexlib** [comment]
thanks, @ErichZimmer for opening the issue. it wasn't too difficult to solve with a bit of Sourceforge :) 

https://openpiv.readthedocs.io/en/latest/src/api_reference.html
