### ISSUE TITLE
No module named 'imageio.v3'

### ISSUE THREAD

**Issue by ZLoverty** [OpenPIV/openpiv-python#244]
**Describe the bug**
I'm using openpiv 0.24.1. In my code, I import the `tools` module with
```
from openpiv import tools, pyprocess, validation, filters, scaling
```
and get the following error
```
    from openpiv import tools, pyprocess, validation, filters, scaling
  File "C:\Users\liuzy\Miniconda3\lib\site-packages\openpiv\tools.py", line 32, in <module>
    from imageio.v3 import imread as _imread, imwrite as _imsave
ModuleNotFoundError: No module named 'imageio.v3'
```

**To Reproduce**
1. `from openpiv import tools`
2. See error `ModuleNotFoundError: No module named 'imageio.v3'`

**Expected behavior**
`imageio` package is on the dependency list, so I guess it's the package that's supposed to be imported.

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by alexlib** [comment]
@ZLoverty I run Windows 10 and cannot reproduce your bug. Please uninstall and reinstall openpiv, e.g. 

`pip install openpiv --upgrade --force-reinstall`

and update us if it solves the problem
