### ISSUE TITLE
Example code for Background-Oriented Schlieren application

### ISSUE THREAD

**Issue by shiba24** [OpenPIV/openpiv-python#250]
**Is your feature request related to a problem? Please describe.**

Dear committers, thank you for this great product!
This is more a feature request or a question.

Recently I am playing around Background-Oriented Schlieren (BOS) imaging, and wondering if you could navigate me with parameters for BOS and its processing.
It would be also great if the tutorial and/or the examples (https://github.com/OpenPIV/openpiv-python-examples) include such a use-case.

A sample dataset can be this one: https://zenodo.org/record/6136052#.Yx8FCuxBxqu . 

**Describe the solution you'd like**
I followed this tutorial https://openpiv.readthedocs.io/en/latest/src/tutorial1.html but the result looks like very weird. I guess I need to tune the input parameters but I don't how to tune. I only could find `scale_factor  = 1 / 0.26` from the dataset description. But other parameters are difficult for newbie like me.

I'm new to PIV and still studying..  Can anyone help me?

Sincerely,

**Comment by alexlib** [comment]
https://deepnote.com/@alex-liberzon/bosvelocimetry-5a409ffc-4365-43ea-9d49-425c249ee983
