### ISSUE TITLE
suggestion: replace np.roll by scipy.ndimage.fourier_shift

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#258]
similar to https://scikit-image.org/docs/stable/auto_examples/registration/plot_register_translation.html#sphx-glr-auto-examples-registration-plot-register-translation-py

it will allow us to use subpixel shifts and more stable and accurate tests

**Comment by ErichZimmer** [comment]
Where do we use this? Only on tests and the basic theory notebook?

**Comment by alexlib** [comment]
only in tests. tests is our weakest point

**Comment by ErichZimmer** [comment]
I suppose I can add more tests, probably in a similar fashion to OpenPIV-Python-cxx, while implementing your idea.
