### ISSUE TITLE
masking 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#260]
Dear All,

I'd like to discuss with you the issue of using masks in openpiv-python. At the moment, we have a mixture of items that we call masks:

1. image mask - masking out a region in the PIV image that is not participating in the analysis, e.g. a cylinder in the flow. Now we have two types of such image masks - static, i.e. supplied upfront to all the images in the series, and dynamic - something that moves in the field of view and we want to mask it at different locations, shapes and sizes in every image pair (it's a joint mask for A, B if the shape changes between A and B).

2. we convert the image mask (not yet in the first_pass, simple_piv, or extended_search_piv) only in multi_pass windef.py to the grid_mask, i.e. True/False marks on the grid of x,y

3. On top of these, we have signal-to-noise and other validation procedures that remove erroneous vectors. If such vectors occupy some region, we do not want them to participate in the window deformation, so they also kind of join the grid_mask by marking out the "invalid" regions.

Then we store all the grid_mask as an additional column to the output file, together with x,y,u,v (or also w), mask. This column is an unclear combination of vector regions that failed to produce a valid region with the regions the user wants to mark as not-to-process.

I'd like to please to hear your opinion on what's your opinion on making these masks more useful for you - please suggest your use cases and explain what would be necessary to keep them in the output file

Thanks,
Alex

**Comment by ErichZimmer** [comment]
Hi Alex,

I personally use masked data in the following way. First, I mask out bad pixels using a static mask generated in ImageJ. After analyzing masked images, I downscale the static mask to the scale of the u/v components. Then, I mark invalid vectors (not masked vectors) with a separate array, flag, and replace them. Finally, I save the results in a .vec file with a title like ``# x y u v s2n flag ismask``. This helps differentiate masked vectors and invalid vectors. 

On invalid vectors, I use a slightly different convention then what is used in OpenPIV-Python where 0 = valid, 1 = invalid, and 2 = interpolated (generated by `replace_nans`). This was inspired by commercial softwares.

### Some suggestions to remove ambiguity in masked data:
 + rename invalid vectors array, mask, to flag
 + add ismask to saved output if static mask is present (e.g. don't mask output vectors when saving unless explicitly done by the user)

**Comment by alexlib** [comment]
> Hi Alex,
> 
> I personally use masked data in the following way. First, I mask out bad pixels using a static mask generated in ImageJ. After analyzing masked images, I downscale the static mask to the scale of the u/v components. Then, I mark invalid vectors (not masked vectors) with a separate array, flag, and replace them. Finally, I save the results in a .vec file with a title like `# x y u v s2n flag ismask`. This helps differentiate masked vectors and invalid vectors.
> 
> On invalid vectors, I use a slightly different convention then what is used in OpenPIV-Python where 0 = valid, 1 = invalid, and 2 = interpolated (generated by `replace_nans`). This was inspired by commercial softwares.
> ### Some suggestions to remove ambiguity in masked data:
> 
>     * rename invalid vectors array, mask, to flag
> 
>     * add ismask to saved output if static mask is present (e.g. don't mask output vectors when saving unless explicitly done by the user)

Thanks @ErichZimmer 

1. now we do more or less the same: we mask the image and use it only for the following mask over the u,v  results
2. in parallel we apply NaNs on invalid vectors and regardless of the image mask, we replace them with inpaint_nans
3. we reapply the image mask at every multi-processing step using the new, refined grid
4. we can save the mask next to u,v, but u,v, is also stored for places that should be masked. There is some issue that this info should propagate to the following usage, where the mask should be reapplied. 

I agree we can add another object, i.e. invalid_flag and keep this flag as 0,1, or 2 or anything else - the question is, what do you do with this later on? is it only for a future report or you actually use this flag in post-processing? 

also we wait for the developers of openpiv_tk_gui @eguvep to say their word :)

**Comment by ErichZimmer** [comment]
Hi Alex,

I use the flags object for post-processing and statistics. As I perform different vector validation algorithms, the invalid flags are all consolidated into one object, which is fed into the replace_nans function. Later, I do a statistical analysis using the flags object and observations of vector fields to change parameters and hopefully attain better results on experiments.

**Comment by alexlib** [comment]
> Hi Alex,
> 
> 
> 
> I use the flags object for post-processing and statistics. As I perform different vector validation algorithms, the invalid flags are all consolidated into one object, which is fed into the replace_nans function. Later, I do a statistical analysis using the flags object and observations of vector fields to change parameters and hopefully attain better results on experiments.


i do not understand how to use it in the multiprocessing are there flags per iteration? don't you interpolate at every iteration with the larger window sizes?

**Comment by ErichZimmer** [comment]
> i do not understand how to use it in the multiprocessing are there flags per iteration? don't you interpolate at every iteration with the larger window sizes?

Flags are per iteration and only the final iteration is stored 
in the .vec file for later use. Since the flags are redefined each iteration, it doesn't matter how you perform multi-pass window deformation evaluations as the flags object would always have the same shape and size as the x/y/u/v components. For instance, here is a basic processing flow.

## Image processing
 - read mask

## First pass
- PIV eval with 128x128 px interrogation windows and 50% overlap
 - grid mask to resolution of vectors 
- validate vectors with global std and local median filter
- consolidate invalid flags into flag array
- replace outliers using flag array
- smooth vector field

## Second pass
- PIV eval with 64x64 px interrogation windows and 50% overlap
- grid mask to resolution of vectors 
- validate vectors with global std and local median filter
- consolidate invalid flags into flag array
- replace outliers using flag array
- smooth vector field

## Third (final) pass
- PIV eval with 32x32 px interrogation windows and 50% overlap
- grid mask to resolution of vectors 
- validate vectors with global std and local median filter
- consolidate invalid flags into flag array
- replace outliers using flag array
- save vectors (x, y, u, v, flag, ismask)

**Comment by alexlib** [comment]
@ErichZimmer please suggest a list of usable flags. meanwhile, I will use 0 - valid, and 1 - invalid (it will be anyhow interpolated at some stage, as we do not leave it untouched usually). Do you want to keep 1 for those that we do not interpolate? it would be rather difficult to find I think.

**Comment by ErichZimmer** [comment]
To be honest, using a boolean flag array is just as useful. The interpolated vs invalid flag is simply used for plotting purposes, so it isn't really necessary. I mainly used it for comparisons with the first, second, and fourth international PIV challenge.

**Comment by alexlib** [comment]
masking is implemented in 0.24.4rc0 and higher
