### ISSUE TITLE
Non even interrogation windows 

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv-python#264]
**Is your feature request related to a problem? Please describe.**
When performing PIV evaluations with odd interrogation window sizes, results are sometimes inaccurate. Furthermore, linear correlation sometimes breaks with odd interrogation windows as peaks are shifted 1 pixel in x and y axis.

**Describe the solution you'd like**
Add an if-statement disabling arbitrary sized interrogation windows and only allowing windows that are a multiple of 2. Another option is to modify the correlation functions to adjust for odd interrogation windows.

**Additional context**
Test was done with synthetic images with the following parameters:
image size: 512 x 512 px
image bitness: 8-bit
flow field: linear
flow magnitude: 1.5 px
number of particles: 10,000
particle profile: gaussian profile
particle mean diameter: 3 px
particle diameter std: 0
particle mean intensity: 255
particle intensity std: 0

![openpiv_int_window_test](https://user-images.githubusercontent.com/69478071/198517062-2e6d7f27-1092-4d2c-8b4e-f17ea55543f3.jpeg)
![openpiv_int_window_test_clipped](https://user-images.githubusercontent.com/69478071/198517076-009a4301-4c74-46a4-9d20-6d6ec554c91e.jpeg)

**Comment by alexlib** [comment]
please @ErichZimmer attach a notebook with this test

**Comment by ErichZimmer** [comment]
Here is the link to a notebook test.
https://github.com/ErichZimmer/test_robustness/blob/main/notebooks/test_correlation.ipynb

**Comment by alexlib** [comment]
> Here is the link to a notebook test. https://github.com/ErichZimmer/test_robustness/blob/main/notebooks/test_correlation.ipynb

I do not see these plots and do not see where the error is coming from 

https://github.com/OpenPIV/test_robustness/blob/alex_test_v025/notebooks/test_correlation.ipynb

**Comment by ErichZimmer** [comment]
It seems that the notebook wasn't uploaded properly, so I'll try again.

**Comment by ErichZimmer** [comment]
The error is from
```python
size = s1 + s2 - 1
        fsize = 2 ** np.ceil(np.log2(size)).astype(int)
        fslice = (slice(0, image_a.shape[0]),
                  slice((fsize[0]-s1[0])//2, (fsize[0]+s1[0])//2),
                  slice((fsize[1]-s1[1])//2, (fsize[1]+s1[1])//2))
```
Setting size to s1+s2 fixes the issue. So does padding the interrogation window to an even number.

**Comment by ErichZimmer** [comment]
Using 
```python
size = s1 + s2 - 1
        fsize = 2 ** np.ceil(np.log2(size)).astype(int) - 1
        fslice = (slice(0, image_a.shape[0]),
                  slice((fsize[0]-s1[0])//2, (fsize[0]+s1[0])//2),
                  slice((fsize[1]-s1[1])//2, (fsize[1]+s1[1])//2))
```
I get this plot:
![possible_fix](https://user-images.githubusercontent.com/69478071/200648289-dbcb9a5c-8fc7-4aa7-932a-2802ffcc4012.jpeg)

**Comment by alexlib** [comment]
Looks great. Let's push the pull request?
