### ISSUE TITLE
Save format undone by commit (back to non-scientific notation)

### ISSUE THREAD

**Issue by hifabian** [OpenPIV/openpiv-python#269]
**Describe the bug**
The commit 7d811952c8c7c7261fac7f371231cd22e162665f undid the change in save format of the commit 18d8414bda8c3bd8731dc4db20034721ca7ab923. That means the output is again saved using 4 fixed decimal points and hence potentially cutting off 'small' velocities and giving inaccurate precision for 'high' velocities.

I mentioned that the commit 18d8414bda8c3bd8731dc4db20034721ca7ab923 might be an aggressive change. But it is absolutely necessary to provide users access to output in scientific notation (to handle wide range of velocities given fixed units). Alternatively, one can provide a `PIVSettings` option `save_format` (or similar name) to set the save format.

**To Reproduce**
Run PIV with save using windef.

**Expected behavior**
Output files use scientific notation.

**Comment by ErichZimmer** [comment]
Should we add a fmt parameter to allow users to select any format? Or would that be to complicated for those who do not understand how to use the fmt parameter? If so, should we make a boolean parameter for scientific notation? I do not know how many users would use these options, but I suppose it would be handy for those who need it. I'll add this on my bucket list for things to get done this coming Thursday or Sunday.

**Comment by alexlib** [comment]
> **Describe the bug** The commit [7d81195](https://github.com/OpenPIV/openpiv-python/commit/7d811952c8c7c7261fac7f371231cd22e162665f) undid the change in save format of the commit [18d8414](https://github.com/OpenPIV/openpiv-python/commit/18d8414bda8c3bd8731dc4db20034721ca7ab923). That means the output is again saved using 4 fixed decimal points and hence potentially cutting off 'small' velocities and giving inaccurate precision for 'high' velocities.
> 
> I mentioned that the commit [18d8414](https://github.com/OpenPIV/openpiv-python/commit/18d8414bda8c3bd8731dc4db20034721ca7ab923) might be an aggressive change. But it is absolutely necessary to provide users access to output in scientific notation (to handle wide range of velocities given fixed units). Alternatively, one can provide a `PIVSettings` option `save_format` (or similar name) to set the save format.
> 
> **To Reproduce** Run PIV with save using windef.
> 
> **Expected behavior** Output files use scientific notation.

my mistake - that wasn't intentional. thanks for noticing

**Comment by alexlib** [comment]
> Should we add a fmt parameter to allow users to select any format? Or would that be to complicated for those who do not understand how to use the fmt parameter? If so, should we make a boolean parameter for scientific notation? I do not know how many users would use these options, but I suppose it would be handy for those who need it. I'll add this on my bucket list for things to get done this coming Thursday or Sunday.

the `tools.save` function has `fmt=".4e"` option, one can change it on the save, but not in `windef` which saves under the hood.
