### ISSUE TITLE
TypeError: sig2noise_val() got multiple values for argument 'threshold'

### ISSUE THREAD

**Issue by cjx2020** [OpenPIV/openpiv-python#286]
When I run the code from http://github.com/openpiv/openpiv-python-example, the jupyter notebook raise above error. I have checked the source code in validation.py, I found the example file provide too many prarmeter in sig2noise_val(). And it's worth noting that the verion of openpiv is 0.25.0. Whether the code file in document is not updated in time ?

<img width="835" alt="微信截图_20230212173314" src="https://user-images.githubusercontent.com/63455193/218303454-a66de75d-f097-4d06-a558-0e55b32e1da6.png">

<img width="708" alt="微信截图_20230212173909" src="https://user-images.githubusercontent.com/63455193/218303616-a6928ff6-05ba-48cc-bd4c-f881c276fc33.png">

**Comment by alexlib** [comment]
Thanks for noticing @cjx2020 - indeed this is an old example (6 years) and it's an old syntax. I'm going to fix it now.

**Comment by cjx2020** [comment]
ok,thank you sir.

**Comment by alexlib** [comment]
Meanwhile, you're welcome to run examples that do work :) 
https://github.com/OpenPIV/openpiv-python-examples

**Comment by cjx2020** [comment]
ok, it works well, thank you.
