### ISSUE TITLE
ImportError: No module named progressbar

### ISSUE THREAD

**Issue by sciunto** [OpenPIV/openpiv-python#29]
Hi,

I donwloaded this sample: http://www.openpiv.net/openpiv-python/_downloads/tutorial-part13.zip

And I got this error:

```
 python2 tutorial-part1.py                                                                                                                        13:47
Traceback (most recent call last):
  File "tutorial-part1.py", line 1, in <module>
    import openpiv.tools
  File "/usr/lib/python2.7/site-packages/openpiv/__init__.py", line 21, in <module>
    import openpiv.process
  File "process.pyx", line 11, in init openpiv.process (openpiv/src/process.c:25074)
ImportError: No module named progressbar

```

**Comment by OverRatedTech** [comment]
It worked! Thank you

**Comment by alexlib** [comment]
we removed progressbar dependence

**Comment by powersem2007** [comment]
it didnt work for e :(

**Comment by alexlib** [comment]
What exactly didn't work?

**Comment by powersem2007** [comment]
i am in visual studio code and it still wont work
i want this
from console_progressbar import ProgressBar

but my terminal says this
Traceback (most recent call last):
  File "c:\Users\SemvM\Desktop\Nieuwe map (3)\admin.py", line 2, in <module>
    from console_progressbar import ProgressBar
ModuleNotFoundError: No module named 'console_progressbar

**Comment by alexlib** [comment]
@powersem2007 this is not related to openpiv-python. you can check yourself - we do not use progressbar anymore for a long time 
https://github.com/OpenPIV/openpiv-python/search?q=ProgressBar

i guess you have somewhat wrong installation. 
please follow our installation recommendations:

`pip install openpiv --force-reinstall --upgrade`

to get an updated and the latest version that definitely does not need progressbar

**Comment by powersem2007** [comment]
i sen you my code so you can help me bc i dont understand i am doing that command now




import socket
from console_progressbar import ProgressBar
import time
import ast

class Emkit:

    def __init__(self, port):
        self.ip = socket.gethostbyname(socket.gethostname())
        self.port = port
        self.s = socket.socket()
        self.pb = ProgressBar(total=100,prefix='', suffix='Now', decimals=3, length=50, fill='X', zfill='-')

    def print_copyright(self):
        self.banner = """
        ███████╗███╗░░░███╗██╗░░██╗██╗████████╗
        ██╔════╝████╗░████║██║░██╔╝██║╚══██╔══╝
        █████╗░░██╔████╔██║█████═╝░██║░░░██║░░░
        ██╔══╝░░██║╚██╔╝██║██╔═██╗░██║░░░██║░░░
        ███████╗██║░╚═╝░██║██║░╚██╗██║░░░██║░░░
        ╚══════╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░░╚═╝░░░
             Made By Semegorden{OS} | v1.0
        """
        print(self.banner)

    def bind_server(self):
        self.pb.print_progress_bar(2)
        self.s.bind((self.ip,self.port))

    def get_command(self):
        pass

root = Emkit(8080)
root.print_copyright()
root.bind_server()
root.get_command()

**Comment by alexlib** [comment]
@powersem2007

you're using something that has nothing to do with openpiv-python. Please stop. Find the software repository you're trying to use and send them your issues. It's not automatically going to every place where the name `progressbar` is mentioned. it's not related to openpiv-python and I close this issue for further discussions.

**Comment by powersem2007** [comment]
oke
