### ISSUE TITLE
Streamplot issue

### ISSUE THREAD

**Issue by chi86** [OpenPIV/openpiv-python#294]
Hi,
when I try to run the command `strm = ax.streamplot(x,y,u,v, color=u, linewidth=2, cmap='autumn') `given in:
https://gist.github.com/alexlib/77d4eef714f75989572debff53157722

I get following error:
```
  File "OpenPIV.py", line 435, in <module>
    strm=ax.streamplot(x,y,u,v, color=u, linewidth=2, cmap='autumn')
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/lib/python3.10/site-packages/matplotlib/streamplot.py", line 91, in streamplot
    grid = Grid(x, y)
  File "/usr/lib/python3.10/site-packages/matplotlib/streamplot.py", line 346, in __init__
    raise ValueError("'y' must be strictly increasing")
ValueError: 'y' must be strictly increasing
```

This used to work the last time I ran it a year ago.....

I use the following:
- Python 3.10.10 (main, Feb 28 2023, 14:28:52) [GCC 11.3.1 20221209] on linux
- matplotlib version = '3.6.2'
- openpiv version 0.25.0

Any help is very much appreciated. Thanks!

**Comment by alexlib** [comment]
See the updated version. 

https://gist.github.com/alexlib/f6855a1d9b53b6b7cd5e9571cc9b826f

**Comment by chi86** [comment]
Thank you very much! This works fine, but this mirrors the display.

**Comment by chi86** [comment]
I found a workaround. Following the steps:
1. Before performing the PIV I mirror the frames `frame_a=frame_a[::-1,:]`
2. After the PIV and the `get_coordinates` I mirror y (`y=-(y-y.max())`) and fix the sign of v0 (`v0=-v0`)

I have same issue with the `pivpy` version.

Thanks for the help!

**Comment by alexlib** [comment]
If possible, share your notebook so things are clear to others
you can fork or suggest on gist 
https://gist.github.com/alexlib/f6855a1d9b53b6b7cd5e9571cc9b826f

**Comment by alexlib** [comment]
here's a fix for pivpy - I need to use the original `x,y,u,v` and not transformed

https://gist.github.com/alexlib/3baa2abecd769f9eac30a57a3bbeb675

**Comment by chi86** [comment]
Here the link to the gist:
https://gist.github.com/chi86/53ba84bf9f5a8626f84c08ef2a905c69

**Comment by alexlib** [comment]
> Here the link to the gist: https://gist.github.com/chi86/53ba84bf9f5a8626f84c08ef2a905c69

I see, but the results are only "visually" correct, not really. You see - the original image has an origin top left and the result you present is bottom left - so the direction of rotation is maybe visually correct, but the values are not. We had quite a long discussion of this issue and decided that we present stuff on image to comply with the visual info - for instance if we play two images, what direction we see? clockwise from A to B frame. But if we consider u,v according to x,y located at 0,0 and we consider vertical upwards as positive v, then the actual result is negative v on the right side and positive v on the left side of the vortex.
