### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'DTYPEi_t' but got 'unsigned char'

### ISSUE THREAD

**Issue by thomasfiala** [OpenPIV/openpiv-python#35]
Hi,
running the tutorial part 1, I get the following error:

```
Traceback (most recent call last):
  File "/Users/tf/Downloads/firefox/tutorial-part1/tutorial-part1.py", line 8, in <module>
u, v, sig2noise = openpiv.process.extended_search_area_piv( frame_a, frame_b, window_size=24, overlap=12, dt=0.02, search_area_size=64, sig2noise_method='peak2peak' )
  File "process.pyx", line 23, in openpiv.process.extended_search_area_piv (openpiv/src/process.c:2392)
ValueError: Buffer dtype mismatch, expected 'DTYPEi_t' but got 'unsigned char'
```

**Comment by julienmsc** [comment]
Hi Alex, in my case, I am still getting the same error mistake, even after your recommendations ...
what could be the problem ?
If you have an idea, let me know ,
thanks, 
Julien

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
building 'openpiv.process' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c openpiv/src/process.c -o build/temp.linux-x86_64-2.7/openpiv/src/process.o
openpiv/src/process.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by alexlib** [comment]
what is the python distribution and Cython version? 

I recommend to install Anaconda Python distribution and then 

conda install cython

to add the latest Cython

**Comment by alexlib** [comment]
I do not know. Let's try another way - let me access your machine on remote
(teamviewer, vnc, whatever) and I'll try to see if I understand the
problem.

**Comment by wtvrinc** [comment]
Was the above issue resolved? I am getting the same error.

**Comment by alexlib** [comment]
can you please, tell me the platform, python version, gcc version, etc.? I do not have any problem on my Ubuntu 12.04LS with gcc4 

the simplest test is 
>> pip install openpiv

this should just work out of the box

**Comment by wtvrinc** [comment]
Hi, I am using Fedora 20, gcc version 4.8.3.
Python 2.7.10 (Anaconda 2.3.0) additional information when I type 'python' in console: GCC 4.4.7. 

I installed anaconda after I saw your instructions. But the problem persisted.

**Comment by alexlib** [comment]
could you please write me offline to alex dot liberzon at gmail dot com - it would be very helpful if we could arrange a teamviewer session and I'll take a look at this bug closely. I cannot install Fedora quickly, so I would better use the machine that already has it.

**Comment by alexlib** [comment]
see OpenPIV v. 0.19 on pypi or github
http://github.com/OpenPIV/openpiv-python

it is now automatically built and tested on Travis-CI, which means that the
errors you mention are platform or something else specific.

**Comment by wtvrinc** [comment]
Thanks a lot. It must be a problem with Fedora 20. I am not sure what though. I will try a few things. 
-Sunil

**Comment by wtvrinc** [comment]
Hi Alex, 
I tried with the test code put up in the google groups. 
https://groups.google.com/forum/#!topic/openpiv-users/FHc0pcmEjyE

It worked. Adding ".astype(np.int32)" to frame a and b worked.

**Comment by alexlib** [comment]
Glad to hear. Thanks for reporting it. We still have to improve the test suite.

**Comment by williamgilpin** [comment]
I am having the same issue on both OSX Yosemite and Windows 8.0, but adding ".astype(np.int32)" to frames "A" and "B" solved the issue. I'm having a similar problem with "replace_outliers" that I'll file a separate bug report for. Thanks for maintaining this awesome package!
