### ISSUE TITLE
setup.py and tools.py

### ISSUE THREAD

**Issue by jb427** [OpenPIV/openpiv-python#70]
Hi,

Installing openpiv on my Ubuntu 14.04 I got the following problem: the default encoding was not utf8. I fixed it with a sys.setdefaultencoding('utf8')

Also, filters has been deprecated in skimage, filter must be loaded in tools.py instead

Thanks to all the team for the hard work on openpiv.

Best,
JB

**Comment by alexlib** [comment]
filters -> filter is updated. thanks

I have no idea how to solve the utf8 issue. reading here I understand I shall not use it as a solution, but does not bring me anywhere

http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by alexlib** [comment]
closed, no clear follow up on the utf8 issue
