### ISSUE TITLE
Error during build (Python 2.7.11)

### ISSUE THREAD

**Issue by agclark12** [OpenPIV/openpiv-python#71]
Am trying to install with Python 2.7.11 (on a Mac OSX 10.11.6) and getting the following error during build:

clang: error: no such file or directory: 'openpiv/src/process.c'
clang: error: no input files
error: command '/usr/bin/clang' failed with exit status 1

Have been trying to work around this, but not making any progress. Any ideas? Thanks.

**Comment by alexlib** [comment]
Could you try to install using conda? 

`conda install -c conda-forge openpiv`

**Comment by agclark12** [comment]
thanks. it seems to install with conda fine. i'm not sure why it won't build with the environment I am using for everything else. i should have everything required. will look into that.

**Comment by alexlib** [comment]
solved using conda
