### ISSUE TITLE
Cython Installation Woes

### ISSUE THREAD

**Issue by leycec** [OpenPIV/openpiv-python#74]
Thanks for the monumental effort in porting OpenPIV to [P|C]ython, Alex and company. Sadly, `pip`-based installation on Ubuntu Linux appears to be... *problematic.*

Specifically, the following Cython-related non-human-readable exception is raised:

```
$ pip2 install OpenPIV
Collecting OpenPIV
  Downloading OpenPIV-0.20.5.tar.gz (22.3MB)
    100% |████████████████████████████████| 22.3MB 76kB/s 
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-AvP7gM/Cython-0.25.2/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HYAigT/OpenPIV/setup.py", line 15, in <module>
        Distribution(dict(setup_requires='Cython'))
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 318, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 375, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 443, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 880, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1107, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HYAigT/OpenPIV/
```

The `Unable to find pgen, not compiling formal grammar.` line is, of course, dangerously suspicious. My intuitive reading of this exception is that the Python 2.7 version of Cython is either *not* currently installed on my system or is installed improperly. I assume the latter, as the equally suspicious line `/tmp/easy_install-AvP7gM/Cython-0.25.2/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory` suggests that `pip2` did at least attempt to install Cython into a temporary directory but failed, probably due to Python 2.7 development headers not having been installed.

A [similar issue elsewhere](https://github.com/alexjc/neural-doodle/issues/16) suggests that manually installing Cython via `apt-get` on Debian-based Linux distributions (e.g., Ubuntu) is the ideal working solution:

```
sudo apt-get install cython
```

Let's give that a whirl.

**Comment by leycec** [comment]
**Excellent.** That sufficed to hurtle me past the Cython error detailed above. It'd be *awesome* if the [installation instructions](https://openpiv.readthedocs.io/en/latest/src/installation_instruction.html) could be improved to suggest the commands for installing OpenPIV under Ubuntu Linux:

```
sudo apt-get install cython numpy scipy
pip2.7 install OpenPIV
```

**Comment by alexlib** [comment]
Thanks for reporting @leycec, but I cannot reproduce the problem

`(test) ivan@ivan-VirtualBox:~/tmp$ pip2 install OpenPIV
Collecting OpenPIV
Collecting cython (from OpenPIV)
  Downloading Cython-0.25.2-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 220kB/s 
Collecting numpy (from OpenPIV)
  Downloading numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 85kB/s 
Installing collected packages: cython, numpy, OpenPIV
Successfully installed OpenPIV-0.20.5 cython-0.25.2 numpy-1.12.1
`

**Comment by leycec** [comment]
**Right.** That's presumably due to either:

* Your platform implicitly installing the Python headers (e.g., the `/usr/include/python3.6m` directory for Python 3.6) out-of-the-box.
* Your having explicitly installed the Python headers manually.

I probably should have been a bit more *explicit* myself above. The core issue here is that:

1. OpenPIV requires Cython which requires the Python headers.
1. For hopefully obvious reasons, `pip2` *cannot* install the Python headers. <sup>..._not that I know of, anyway. That'd be pretty crazy if it could._</sup>
1. The Python headers are *not* installed on most Linux distributions by default – including Ubuntu Linux, the most popular Linux distribution.
1. Ergo, `pip2` cannot install OpenPIV on most Linux distributions out-of-the-box.

**Comment by alexlib** [comment]
Thanks. I got it, finally. 

Updated both the installation instructions and the Readme. However, I think that it's not written now clear enough, so I leave this issue open for the future users that might find here the motivation for the better installation instructions and/or packaging as you suggest.
