### ISSUE TITLE
setup.py Fails to List scikit-image as a Dependency 

### ISSUE THREAD

**Issue by leycec** [OpenPIV/openpiv-python#86]
*Aaaaaand...* here we go again.

The `openpiv.tools` submodule imports `skimage`, the top-most package for the external [`scikit-image` project](http://scikit-image.org). That project is thus a hard dependency of OpenPIV and should be listed as such in this project's `setup.py` script.

Since OpenPIV requires the `skimage.filters` submodule first introduced with `scikit-image` 0.12.0 (...*I think?*), it would probably be helpful to constrain this dependency in a version-specific manner: e.g.,

    install_requires = ['scipy','numpy','cython','scikit-image >= 0.12.0'],

And thanks for your continual efforts on the Python front. Python is *really* the scientific future. It's great to see OpenPIV adopting and embracing the new standard! :1st_place_medal:

**Comment by alexlib** [comment]
resolved in #87
