### ISSUE TITLE
multi-pass_tutorial not working

### ISSUE THREAD

**Issue by clarka34** [OpenPIV/openpiv-python#99]
The jupyter notebook in the multi-pass_tutorial is no longer working. 

1. Some missing imports
2. The PIV module no longer exists
3. There is a bug in WiDIM that I cannot seem to figure out (IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices)

I would be happy to update the tutorial once I know how to fix the issue with WiDIM.

**Comment by alexlib** [comment]
Hi @clarka34 could you please see if the WIDIM has been fixed in the widim branch ? https://github.com/alexlib/openpiv-python/tree/widim

if so, it would be very helpful if you update the files. The development was done by @CameronDallas5000  see 2e52b08ee7e6692a5d42bb3777f28a6935b588f9

**Comment by alexlib** [comment]
see the latest commit PR #100 is resolving WIDIM and other tutorial issues
